# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_create_orders(self) -> None:
        """Test case for create_orders

        Create a sale order 🔐
        """
        pass

    def test_list_orders(self) -> None:
        """Test case for list_orders

        List orders 🔐
        """
        pass

    def test_orders_close(self) -> None:
        """Test case for orders_close

        Close an order (Classify it as \"Delivered\") 🔐
        """
        pass

    def test_orders_create_contact(self) -> None:
        """Test case for orders_create_contact

        Add a contact type of given order 🔐
        """
        pass

    def test_orders_create_line(self) -> None:
        """Test case for orders_create_line

        Add a line to given order 🔐
        """
        pass

    def test_orders_create_order_from_proposal(self) -> None:
        """Test case for orders_create_order_from_proposal

        Create an order using an existing proposal. 🔐
        """
        pass

    def test_orders_create_order_shipment(self) -> None:
        """Test case for orders_create_order_shipment

        Create the shipment of an order 🔐
        """
        pass

    def test_orders_remove_contact(self) -> None:
        """Test case for orders_remove_contact

        Unlink a contact type of given order 🔐
        """
        pass

    def test_orders_remove_line(self) -> None:
        """Test case for orders_remove_line

        Delete a line of a given order 🔐
        """
        pass

    def test_orders_reopen(self) -> None:
        """Test case for orders_reopen

        Tag the order as validated (opened) 🔐
        """
        pass

    def test_orders_retrieve_by_ref(self) -> None:
        """Test case for orders_retrieve_by_ref

        Get properties of an order object by ref 🔐
        """
        pass

    def test_orders_retrieve_by_ref_ext(self) -> None:
        """Test case for orders_retrieve_by_ref_ext

        Get properties of an order object by ref_ext 🔐
        """
        pass

    def test_orders_retrieve_contacts(self) -> None:
        """Test case for orders_retrieve_contacts

        Get contacts of given order 🔐
        """
        pass

    def test_orders_retrieve_line(self) -> None:
        """Test case for orders_retrieve_line

        Get properties of a line of an order object by id 🔐
        """
        pass

    def test_orders_retrieve_lines(self) -> None:
        """Test case for orders_retrieve_lines

        Get lines of an order 🔐
        """
        pass

    def test_orders_retrieve_order_shipments(self) -> None:
        """Test case for orders_retrieve_order_shipments

        Get the shipments of an order 🔐
        """
        pass

    def test_orders_setinvoiced(self) -> None:
        """Test case for orders_setinvoiced

        Classify the order as invoiced. Could be also called setbilled 🔐
        """
        pass

    def test_orders_settodraft(self) -> None:
        """Test case for orders_settodraft

        Set an order to draft 🔐
        """
        pass

    def test_orders_update_line(self) -> None:
        """Test case for orders_update_line

        Update a line to given order 🔐
        """
        pass

    def test_orders_validate(self) -> None:
        """Test case for orders_validate

        Validate an order 🔐
        """
        pass

    def test_remove_orders(self) -> None:
        """Test case for remove_orders

        Delete order 🔐
        """
        pass

    def test_retrieve_orders(self) -> None:
        """Test case for retrieve_orders

        Get properties of an order object by id 🔐
        """
        pass

    def test_update_orders(self) -> None:
        """Test case for update_orders

        Update order general fields (won't touch lines of order) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
