# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.memberstypes_api import MemberstypesApi


class TestMemberstypesApi(unittest.TestCase):
    """MemberstypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberstypesApi()

    def tearDown(self) -> None:
        pass

    def test_create_memberstypes(self) -> None:
        """Test case for create_memberstypes

        Create member type object 🔐
        """
        pass

    def test_list_memberstypes(self) -> None:
        """Test case for list_memberstypes

        List members types 🔐
        """
        pass

    def test_remove_memberstypes(self) -> None:
        """Test case for remove_memberstypes

        Delete member type 🔐
        """
        pass

    def test_retrieve_memberstypes(self) -> None:
        """Test case for retrieve_memberstypes

        Get properties of a member type object 🔐
        """
        pass

    def test_update_memberstypes(self) -> None:
        """Test case for update_memberstypes

        Update member type 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
