# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.agendaevents_api import AgendaeventsApi


class TestAgendaeventsApi(unittest.TestCase):
    """AgendaeventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgendaeventsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agendaevents(self) -> None:
        """Test case for create_agendaevents

        Create an agenda event 🔐
        """
        pass

    def test_list_agendaevents(self) -> None:
        """Test case for list_agendaevents

        List agenda events 🔐
        """
        pass

    def test_remove_agendaevents(self) -> None:
        """Test case for remove_agendaevents

        Delete an agenda event 🔐
        """
        pass

    def test_retrieve_agendaevents(self) -> None:
        """Test case for retrieve_agendaevents

        Get agenda event 🔐
        """
        pass

    def test_update_agendaevents(self) -> None:
        """Test case for update_agendaevents

        Update an agenda event 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
