# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_create_tasks(self) -> None:
        """Test case for create_tasks

        Create task object 🔐
        """
        pass

    def test_list_tasks(self) -> None:
        """Test case for list_tasks

        List tasks 🔐
        """
        pass

    def test_remove_tasks(self) -> None:
        """Test case for remove_tasks

        Delete task 🔐
        """
        pass

    def test_retrieve_tasks(self) -> None:
        """Test case for retrieve_tasks

        Get properties of a task object 🔐
        """
        pass

    def test_tasks_add_time_spent(self) -> None:
        """Test case for tasks_add_time_spent

        Add time spent to a task of a project. 🔐
        """
        pass

    def test_tasks_remove_time_spent(self) -> None:
        """Test case for tasks_remove_time_spent

        Delete time spent for a task of a project. 🔐
        """
        pass

    def test_tasks_retrieve_roles(self) -> None:
        """Test case for tasks_retrieve_roles

        Get roles a user is assigned to a task with 🔐
        """
        pass

    def test_tasks_timespent_record_checks(self) -> None:
        """Test case for tasks_timespent_record_checks

        Validate task & timespent IDs for timespent API methods. 🔐
        """
        pass

    def test_tasks_update_time_spent(self) -> None:
        """Test case for tasks_update_time_spent

        Update time spent for a task of a project. 🔐
        """
        pass

    def test_update_tasks(self) -> None:
        """Test case for update_tasks

        Update task general fields (won't touch time spent of task) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
