# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.salaries_api import SalariesApi


class TestSalariesApi(unittest.TestCase):
    """SalariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalariesApi()

    def tearDown(self) -> None:
        pass

    def test_create_salaries(self) -> None:
        """Test case for create_salaries

        Create salary object 🔐
        """
        pass

    def test_list_salaries(self) -> None:
        """Test case for list_salaries

        Get the list of salaries. 🔐
        """
        pass

    def test_retrieve_salaries(self) -> None:
        """Test case for retrieve_salaries

        Get salary by ID. 🔐
        """
        pass

    def test_salaries_add_payment(self) -> None:
        """Test case for salaries_add_payment

        Create payment salary on a salary 🔐
        """
        pass

    def test_salaries_retrieve_all_payments(self) -> None:
        """Test case for salaries_retrieve_all_payments

        Get the list of payment of salaries. 🔐
        """
        pass

    def test_salaries_retrieve_payments(self) -> None:
        """Test case for salaries_retrieve_payments

        Get a given payment. 🔐
        """
        pass

    def test_salaries_update_payment(self) -> None:
        """Test case for salaries_update_payment

        Update paymentsalary 🔐
        """
        pass

    def test_update_salaries(self) -> None:
        """Test case for update_salaries

        Update salary 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
