# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.supplierproposals_api import SupplierproposalsApi


class TestSupplierproposalsApi(unittest.TestCase):
    """SupplierproposalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SupplierproposalsApi()

    def tearDown(self) -> None:
        pass

    def test_create_supplierproposals(self) -> None:
        """Test case for create_supplierproposals

        Create supplier proposal (price request) object 🔐
        """
        pass

    def test_list_supplierproposals(self) -> None:
        """Test case for list_supplierproposals

        List supplier proposals 🔐
        """
        pass

    def test_remove_supplierproposals(self) -> None:
        """Test case for remove_supplierproposals

        Delete commercial proposal 🔐
        """
        pass

    def test_retrieve_supplierproposals(self) -> None:
        """Test case for retrieve_supplierproposals

        Get properties of a supplier proposal (price request) object 🔐
        """
        pass

    def test_update_supplierproposals(self) -> None:
        """Test case for update_supplierproposals

        Update supplier proposal general fields (won't touch lines of supplier proposal) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
