# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_contacts_add_category(self) -> None:
        """Test case for contacts_add_category

        Add a category to a contact 🔐
        """
        pass

    def test_contacts_create_user(self) -> None:
        """Test case for contacts_create_user

        Create a user account object from contact (external user) 🔐
        """
        pass

    def test_contacts_remove_category(self) -> None:
        """Test case for contacts_remove_category

        Remove the link between a category and a contact 🔐
        """
        pass

    def test_contacts_retrieve_by_email(self) -> None:
        """Test case for contacts_retrieve_by_email

        Get a contact by Email 🔐
        """
        pass

    def test_contacts_retrieve_categories(self) -> None:
        """Test case for contacts_retrieve_categories

        Get categories of a contact 🔐
        """
        pass

    def test_create_contacts(self) -> None:
        """Test case for create_contacts

        Create a contact 🔐
        """
        pass

    def test_list_contacts(self) -> None:
        """Test case for list_contacts

        List contacts 🔐
        """
        pass

    def test_remove_contacts(self) -> None:
        """Test case for remove_contacts

        Delete a contact 🔐
        """
        pass

    def test_retrieve_contacts(self) -> None:
        """Test case for retrieve_contacts

        Get a contact 🔐
        """
        pass

    def test_update_contacts(self) -> None:
        """Test case for update_contacts

        Update a contact 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
