# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.objectlinks_api import ObjectlinksApi


class TestObjectlinksApi(unittest.TestCase):
    """ObjectlinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectlinksApi()

    def tearDown(self) -> None:
        pass

    def test_objectlinks_create(self) -> None:
        """Test case for objectlinks_create

        Create object link 🔐
        """
        pass

    def test_objectlinks_remove_by_id(self) -> None:
        """Test case for objectlinks_remove_by_id

        Delete an object link 🔐
        """
        pass

    def test_objectlinks_remove_by_values(self) -> None:
        """Test case for objectlinks_remove_by_values

        Delete object link By Values, not id 🔐
        """
        pass

    def test_objectlinks_retrieve_by_id(self) -> None:
        """Test case for objectlinks_retrieve_by_id

        Get properties of a ObjectLink object 🔐
        """
        pass

    def test_objectlinks_retrieve_by_values(self) -> None:
        """Test case for objectlinks_retrieve_by_values

        GET object link(s) By Values, not id 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
