# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.shipments_api import ShipmentsApi


class TestShipmentsApi(unittest.TestCase):
    """ShipmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShipmentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_shipments(self) -> None:
        """Test case for create_shipments

        Create shipment object 🔐
        """
        pass

    def test_list_shipments(self) -> None:
        """Test case for list_shipments

        List shipments 🔐
        """
        pass

    def test_remove_shipments(self) -> None:
        """Test case for remove_shipments

        Delete shipment 🔐
        """
        pass

    def test_retrieve_shipments(self) -> None:
        """Test case for retrieve_shipments

        Get properties of a shipment object 🔐
        """
        pass

    def test_shipments_close(self) -> None:
        """Test case for shipments_close

        Close a shipment (Classify it as \"Delivered\") 🔐
        """
        pass

    def test_shipments_remove_line(self) -> None:
        """Test case for shipments_remove_line

        Delete a line to given shipment 🔐
        """
        pass

    def test_shipments_validate(self) -> None:
        """Test case for shipments_validate

        Validate a shipment 🔐
        """
        pass

    def test_update_shipments(self) -> None:
        """Test case for update_shipments

        Update shipment general fields (won't touch lines of shipment) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
