# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.multicurrencies_api import MulticurrenciesApi


class TestMulticurrenciesApi(unittest.TestCase):
    """MulticurrenciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MulticurrenciesApi()

    def tearDown(self) -> None:
        pass

    def test_create_multicurrencies(self) -> None:
        """Test case for create_multicurrencies

        Create Currency object 🔐
        """
        pass

    def test_list_multicurrencies(self) -> None:
        """Test case for list_multicurrencies

        List Currencies 🔐
        """
        pass

    def test_multicurrencies_retrieve_by_code(self) -> None:
        """Test case for multicurrencies_retrieve_by_code

        Get properties of a Currency object by code 🔐
        """
        pass

    def test_multicurrencies_retrieve_rates(self) -> None:
        """Test case for multicurrencies_retrieve_rates

        List Currency rates 🔐
        """
        pass

    def test_multicurrencies_update_rate(self) -> None:
        """Test case for multicurrencies_update_rate

        Update Currency rate 🔐
        """
        pass

    def test_remove_multicurrencies(self) -> None:
        """Test case for remove_multicurrencies

        Delete Currency 🔐
        """
        pass

    def test_retrieve_multicurrencies(self) -> None:
        """Test case for retrieve_multicurrencies

        Get properties of a Currency object 🔐
        """
        pass

    def test_update_multicurrencies(self) -> None:
        """Test case for update_multicurrencies

        Update Currency 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
