# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.expensereports_api import ExpensereportsApi


class TestExpensereportsApi(unittest.TestCase):
    """ExpensereportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpensereportsApi()

    def tearDown(self) -> None:
        pass

    def test_create_expensereports(self) -> None:
        """Test case for create_expensereports

        Create an expense report 🔐
        """
        pass

    def test_expensereports_add_payment(self) -> None:
        """Test case for expensereports_add_payment

        Create a payment for an expense report 🔐
        """
        pass

    def test_expensereports_approve(self) -> None:
        """Test case for expensereports_approve

        Approve an expense report 🔐
        """
        pass

    def test_expensereports_deny(self) -> None:
        """Test case for expensereports_deny

        Deny an expense report 🔐
        """
        pass

    def test_expensereports_retrieve_all_payments(self) -> None:
        """Test case for expensereports_retrieve_all_payments

        Get the list of payments of an expense report 🔐
        """
        pass

    def test_expensereports_retrieve_payments(self) -> None:
        """Test case for expensereports_retrieve_payments

        Get an expense report payment 🔐
        """
        pass

    def test_expensereports_update_payment(self) -> None:
        """Test case for expensereports_update_payment

        Update a payment of an expense report 🔐
        """
        pass

    def test_expensereports_validate(self) -> None:
        """Test case for expensereports_validate

        Validate an expense report 🔐
        """
        pass

    def test_list_expensereports(self) -> None:
        """Test case for list_expensereports

        List expense reports 🔐
        """
        pass

    def test_remove_expensereports(self) -> None:
        """Test case for remove_expensereports

        Delete expense report 🔐
        """
        pass

    def test_retrieve_expensereports(self) -> None:
        """Test case for retrieve_expensereports

        Get an expense report 🔐
        """
        pass

    def test_update_expensereports(self) -> None:
        """Test case for update_expensereports

        Update expense report general fields 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
