# coding: utf-8

# flake8: noqa

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountancyApi",
    "AgendaeventsApi",
    "BankaccountsApi",
    "CategoriesApi",
    "ContactsApi",
    "ContractsApi",
    "DocumentsApi",
    "DonationsApi",
    "EventattendeesApi",
    "ExpensereportsApi",
    "InterventionsApi",
    "InvoicesApi",
    "KnowledgemanagementApi",
    "LoginApi",
    "MembersApi",
    "MemberstypesApi",
    "MulticurrenciesApi",
    "ObjectlinksApi",
    "OrdersApi",
    "PartnershipsApi",
    "ProductsApi",
    "ProjectsApi",
    "ProposalsApi",
    "RecruitmentsApi",
    "SalariesApi",
    "SetupApi",
    "ShipmentsApi",
    "StatusApi",
    "StockmovementsApi",
    "SubscriptionsApi",
    "SupplierinvoicesApi",
    "SupplierordersApi",
    "SupplierproposalsApi",
    "TasksApi",
    "ThirdpartiesApi",
    "TicketsApi",
    "UsersApi",
    "WarehousesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BankaccountsAddLineModel",
    "BankaccountsAddLinkModel",
    "BankaccountsTransferModel",
    "BankaccountsUpdateLineModel",
    "ContactsCreateUserModel",
    "ContractsActivateLineModel",
    "ContractsCloseModel",
    "ContractsCreateLineModel",
    "ContractsUnactivateLineModel",
    "ContractsUpdateLineModel",
    "ContractsValidateModel",
    "CreateAgendaeventsModel",
    "CreateBankaccountsModel",
    "CreateCategoriesModel",
    "CreateContactsModel",
    "CreateContractsModel",
    "CreateDocumentsModel",
    "CreateDonationsModel",
    "CreateEventattendeesModel",
    "CreateExpensereportsModel",
    "CreateInterventionsModel",
    "CreateInvoicesModel",
    "CreateKnowledgemanagementModel",
    "CreateMembersModel",
    "CreateMemberstypesModel",
    "CreateMulticurrenciesModel",
    "CreateOrdersModel",
    "CreatePartnershipsModel",
    "CreateProductsModel",
    "CreateProjectsModel",
    "CreateProposalsModel",
    "CreateSalariesModel",
    "CreateShipmentsModel",
    "CreateStockmovementsModel",
    "CreateSubscriptionsModel",
    "CreateSupplierinvoicesModel",
    "CreateSupplierordersModel",
    "CreateSupplierproposalsModel",
    "CreateTasksModel",
    "CreateThirdpartiesModel",
    "CreateTicketsModel",
    "CreateUsersModel",
    "CreateWarehousesModel",
    "DocumentsBuilddocModel",
    "DonationsValidateModel",
    "EventattendeesUpdateByIdModel",
    "EventattendeesUpdateByRefModel",
    "ExpensereportsAddPaymentModel",
    "ExpensereportsApproveModel",
    "ExpensereportsDenyModel",
    "ExpensereportsUpdatePaymentModel",
    "ExpensereportsValidateModel",
    "InterventionsCreateLineModel",
    "InterventionsValidateModel",
    "InvoicesAddContactModel",
    "InvoicesAddPaymentDistributedModel",
    "InvoicesAddPaymentModel",
    "InvoicesCreateLineModel",
    "InvoicesSettodraftModel",
    "InvoicesSettopaidModel",
    "InvoicesUpdateLineModel",
    "InvoicesUpdatePaymentModel",
    "InvoicesValidateModel",
    "KnowledgemanagementCancelModel",
    "KnowledgemanagementValidateModel",
    "ListLoginModel",
    "MembersCreateSubscriptionModel",
    "MembersCreateTypeModel",
    "MembersUpdateTypeModel",
    "MulticurrenciesUpdateRateModel",
    "Obj",
    "ObjectlinksCreateModel",
    "OrdersCloseModel",
    "OrdersCreateLineModel",
    "OrdersSettodraftModel",
    "OrdersUpdateLineModel",
    "OrdersValidateModel",
    "ProductsAddAttributeValueModel",
    "ProductsAddAttributesModel",
    "ProductsAddPurchasePriceModel",
    "ProductsAddSubproductsModel",
    "ProductsAddVariantByProductRefModel",
    "ProductsAddVariantModel",
    "ProductsUpdateAttributeValueModel",
    "ProductsUpdateAttributesModel",
    "ProductsUpdateVariantModel",
    "ProjectsValidateModel",
    "ProposalsCloseModel",
    "ProposalsCreateLineModel",
    "ProposalsCreateLinesModel",
    "ProposalsUpdateLineModel",
    "ProposalsValidateModel",
    "RecruitmentsCreateCandidatureModel",
    "RecruitmentsCreateJobPositionModel",
    "RecruitmentsUpdateCandidatureModel",
    "RecruitmentsUpdateJobPositionModel",
    "SalariesAddPaymentModel",
    "SalariesUpdatePaymentModel",
    "SetupCreateExtrafieldsModel",
    "SetupUpdateExtrafieldsModel",
    "ShipmentsCloseModel",
    "ShipmentsValidateModel",
    "SupplierinvoicesAddPaymentModel",
    "SupplierinvoicesCreateLineModel",
    "SupplierinvoicesSettodraftModel",
    "SupplierinvoicesUpdateLineModel",
    "SupplierinvoicesValidateModel",
    "SupplierordersApproveModel",
    "SupplierordersMakeOrderModel",
    "SupplierordersReceiveOrderModel",
    "SupplierordersValidateModel",
    "TasksAddTimeSpentModel",
    "TasksUpdateTimeSpentModel",
    "ThirdpartiesCreateCompanyBankAccountModel",
    "ThirdpartiesCreateCompanyNotificationByCodeModel",
    "ThirdpartiesCreateCompanyNotificationModel",
    "ThirdpartiesCreateSocieteAccountModel",
    "ThirdpartiesUpdateCompanyBankAccountModel",
    "ThirdpartiesUpdateCompanyNotificationModel",
    "ThirdpartiesUpdateSocieteAccountModel",
    "TicketsCreateNewMessageModel",
    "UpdateAgendaeventsModel",
    "UpdateBankaccountsModel",
    "UpdateCategoriesModel",
    "UpdateContactsModel",
    "UpdateContractsModel",
    "UpdateDonationsModel",
    "UpdateExpensereportsModel",
    "UpdateInterventionsModel",
    "UpdateInvoicesModel",
    "UpdateKnowledgemanagementModel",
    "UpdateMembersModel",
    "UpdateMemberstypesModel",
    "UpdateMulticurrenciesModel",
    "UpdateOrdersModel",
    "UpdatePartnershipsModel",
    "UpdateProductsModel",
    "UpdateProjectsModel",
    "UpdateProposalsModel",
    "UpdateSalariesModel",
    "UpdateShipmentsModel",
    "UpdateSubscriptionsModel",
    "UpdateSupplierinvoicesModel",
    "UpdateSupplierordersModel",
    "UpdateSupplierproposalsModel",
    "UpdateTasksModel",
    "UpdateThirdpartiesModel",
    "UpdateTicketsModel",
    "UpdateUsersModel",
    "UpdateWarehousesModel",
    "UsersCreateUserNotificationByCodeModel",
    "UsersCreateUserNotificationModel",
    "UsersUpdateUserNotificationModel",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from dolibarr_api.api.accountancy_api import AccountancyApi as AccountancyApi
    from dolibarr_api.api.agendaevents_api import AgendaeventsApi as AgendaeventsApi
    from dolibarr_api.api.bankaccounts_api import BankaccountsApi as BankaccountsApi
    from dolibarr_api.api.categories_api import CategoriesApi as CategoriesApi
    from dolibarr_api.api.contacts_api import ContactsApi as ContactsApi
    from dolibarr_api.api.contracts_api import ContractsApi as ContractsApi
    from dolibarr_api.api.documents_api import DocumentsApi as DocumentsApi
    from dolibarr_api.api.donations_api import DonationsApi as DonationsApi
    from dolibarr_api.api.eventattendees_api import EventattendeesApi as EventattendeesApi
    from dolibarr_api.api.expensereports_api import ExpensereportsApi as ExpensereportsApi
    from dolibarr_api.api.interventions_api import InterventionsApi as InterventionsApi
    from dolibarr_api.api.invoices_api import InvoicesApi as InvoicesApi
    from dolibarr_api.api.knowledgemanagement_api import KnowledgemanagementApi as KnowledgemanagementApi
    from dolibarr_api.api.login_api import LoginApi as LoginApi
    from dolibarr_api.api.members_api import MembersApi as MembersApi
    from dolibarr_api.api.memberstypes_api import MemberstypesApi as MemberstypesApi
    from dolibarr_api.api.multicurrencies_api import MulticurrenciesApi as MulticurrenciesApi
    from dolibarr_api.api.objectlinks_api import ObjectlinksApi as ObjectlinksApi
    from dolibarr_api.api.orders_api import OrdersApi as OrdersApi
    from dolibarr_api.api.partnerships_api import PartnershipsApi as PartnershipsApi
    from dolibarr_api.api.products_api import ProductsApi as ProductsApi
    from dolibarr_api.api.projects_api import ProjectsApi as ProjectsApi
    from dolibarr_api.api.proposals_api import ProposalsApi as ProposalsApi
    from dolibarr_api.api.recruitments_api import RecruitmentsApi as RecruitmentsApi
    from dolibarr_api.api.salaries_api import SalariesApi as SalariesApi
    from dolibarr_api.api.setup_api import SetupApi as SetupApi
    from dolibarr_api.api.shipments_api import ShipmentsApi as ShipmentsApi
    from dolibarr_api.api.status_api import StatusApi as StatusApi
    from dolibarr_api.api.stockmovements_api import StockmovementsApi as StockmovementsApi
    from dolibarr_api.api.subscriptions_api import SubscriptionsApi as SubscriptionsApi
    from dolibarr_api.api.supplierinvoices_api import SupplierinvoicesApi as SupplierinvoicesApi
    from dolibarr_api.api.supplierorders_api import SupplierordersApi as SupplierordersApi
    from dolibarr_api.api.supplierproposals_api import SupplierproposalsApi as SupplierproposalsApi
    from dolibarr_api.api.tasks_api import TasksApi as TasksApi
    from dolibarr_api.api.thirdparties_api import ThirdpartiesApi as ThirdpartiesApi
    from dolibarr_api.api.tickets_api import TicketsApi as TicketsApi
    from dolibarr_api.api.users_api import UsersApi as UsersApi
    from dolibarr_api.api.warehouses_api import WarehousesApi as WarehousesApi
    
    # import ApiClient
    from dolibarr_api.api_response import ApiResponse as ApiResponse
    from dolibarr_api.api_client import ApiClient as ApiClient
    from dolibarr_api.configuration import Configuration as Configuration
    from dolibarr_api.exceptions import OpenApiException as OpenApiException
    from dolibarr_api.exceptions import ApiTypeError as ApiTypeError
    from dolibarr_api.exceptions import ApiValueError as ApiValueError
    from dolibarr_api.exceptions import ApiKeyError as ApiKeyError
    from dolibarr_api.exceptions import ApiAttributeError as ApiAttributeError
    from dolibarr_api.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from dolibarr_api.models.bankaccounts_add_line_model import BankaccountsAddLineModel as BankaccountsAddLineModel
    from dolibarr_api.models.bankaccounts_add_link_model import BankaccountsAddLinkModel as BankaccountsAddLinkModel
    from dolibarr_api.models.bankaccounts_transfer_model import BankaccountsTransferModel as BankaccountsTransferModel
    from dolibarr_api.models.bankaccounts_update_line_model import BankaccountsUpdateLineModel as BankaccountsUpdateLineModel
    from dolibarr_api.models.contacts_create_user_model import ContactsCreateUserModel as ContactsCreateUserModel
    from dolibarr_api.models.contracts_activate_line_model import ContractsActivateLineModel as ContractsActivateLineModel
    from dolibarr_api.models.contracts_close_model import ContractsCloseModel as ContractsCloseModel
    from dolibarr_api.models.contracts_create_line_model import ContractsCreateLineModel as ContractsCreateLineModel
    from dolibarr_api.models.contracts_unactivate_line_model import ContractsUnactivateLineModel as ContractsUnactivateLineModel
    from dolibarr_api.models.contracts_update_line_model import ContractsUpdateLineModel as ContractsUpdateLineModel
    from dolibarr_api.models.contracts_validate_model import ContractsValidateModel as ContractsValidateModel
    from dolibarr_api.models.create_agendaevents_model import CreateAgendaeventsModel as CreateAgendaeventsModel
    from dolibarr_api.models.create_bankaccounts_model import CreateBankaccountsModel as CreateBankaccountsModel
    from dolibarr_api.models.create_categories_model import CreateCategoriesModel as CreateCategoriesModel
    from dolibarr_api.models.create_contacts_model import CreateContactsModel as CreateContactsModel
    from dolibarr_api.models.create_contracts_model import CreateContractsModel as CreateContractsModel
    from dolibarr_api.models.create_documents_model import CreateDocumentsModel as CreateDocumentsModel
    from dolibarr_api.models.create_donations_model import CreateDonationsModel as CreateDonationsModel
    from dolibarr_api.models.create_eventattendees_model import CreateEventattendeesModel as CreateEventattendeesModel
    from dolibarr_api.models.create_expensereports_model import CreateExpensereportsModel as CreateExpensereportsModel
    from dolibarr_api.models.create_interventions_model import CreateInterventionsModel as CreateInterventionsModel
    from dolibarr_api.models.create_invoices_model import CreateInvoicesModel as CreateInvoicesModel
    from dolibarr_api.models.create_knowledgemanagement_model import CreateKnowledgemanagementModel as CreateKnowledgemanagementModel
    from dolibarr_api.models.create_members_model import CreateMembersModel as CreateMembersModel
    from dolibarr_api.models.create_memberstypes_model import CreateMemberstypesModel as CreateMemberstypesModel
    from dolibarr_api.models.create_multicurrencies_model import CreateMulticurrenciesModel as CreateMulticurrenciesModel
    from dolibarr_api.models.create_orders_model import CreateOrdersModel as CreateOrdersModel
    from dolibarr_api.models.create_partnerships_model import CreatePartnershipsModel as CreatePartnershipsModel
    from dolibarr_api.models.create_products_model import CreateProductsModel as CreateProductsModel
    from dolibarr_api.models.create_projects_model import CreateProjectsModel as CreateProjectsModel
    from dolibarr_api.models.create_proposals_model import CreateProposalsModel as CreateProposalsModel
    from dolibarr_api.models.create_salaries_model import CreateSalariesModel as CreateSalariesModel
    from dolibarr_api.models.create_shipments_model import CreateShipmentsModel as CreateShipmentsModel
    from dolibarr_api.models.create_stockmovements_model import CreateStockmovementsModel as CreateStockmovementsModel
    from dolibarr_api.models.create_subscriptions_model import CreateSubscriptionsModel as CreateSubscriptionsModel
    from dolibarr_api.models.create_supplierinvoices_model import CreateSupplierinvoicesModel as CreateSupplierinvoicesModel
    from dolibarr_api.models.create_supplierorders_model import CreateSupplierordersModel as CreateSupplierordersModel
    from dolibarr_api.models.create_supplierproposals_model import CreateSupplierproposalsModel as CreateSupplierproposalsModel
    from dolibarr_api.models.create_tasks_model import CreateTasksModel as CreateTasksModel
    from dolibarr_api.models.create_thirdparties_model import CreateThirdpartiesModel as CreateThirdpartiesModel
    from dolibarr_api.models.create_tickets_model import CreateTicketsModel as CreateTicketsModel
    from dolibarr_api.models.create_users_model import CreateUsersModel as CreateUsersModel
    from dolibarr_api.models.create_warehouses_model import CreateWarehousesModel as CreateWarehousesModel
    from dolibarr_api.models.documents_builddoc_model import DocumentsBuilddocModel as DocumentsBuilddocModel
    from dolibarr_api.models.donations_validate_model import DonationsValidateModel as DonationsValidateModel
    from dolibarr_api.models.eventattendees_update_by_id_model import EventattendeesUpdateByIdModel as EventattendeesUpdateByIdModel
    from dolibarr_api.models.eventattendees_update_by_ref_model import EventattendeesUpdateByRefModel as EventattendeesUpdateByRefModel
    from dolibarr_api.models.expensereports_add_payment_model import ExpensereportsAddPaymentModel as ExpensereportsAddPaymentModel
    from dolibarr_api.models.expensereports_approve_model import ExpensereportsApproveModel as ExpensereportsApproveModel
    from dolibarr_api.models.expensereports_deny_model import ExpensereportsDenyModel as ExpensereportsDenyModel
    from dolibarr_api.models.expensereports_update_payment_model import ExpensereportsUpdatePaymentModel as ExpensereportsUpdatePaymentModel
    from dolibarr_api.models.expensereports_validate_model import ExpensereportsValidateModel as ExpensereportsValidateModel
    from dolibarr_api.models.interventions_create_line_model import InterventionsCreateLineModel as InterventionsCreateLineModel
    from dolibarr_api.models.interventions_validate_model import InterventionsValidateModel as InterventionsValidateModel
    from dolibarr_api.models.invoices_add_contact_model import InvoicesAddContactModel as InvoicesAddContactModel
    from dolibarr_api.models.invoices_add_payment_distributed_model import InvoicesAddPaymentDistributedModel as InvoicesAddPaymentDistributedModel
    from dolibarr_api.models.invoices_add_payment_model import InvoicesAddPaymentModel as InvoicesAddPaymentModel
    from dolibarr_api.models.invoices_create_line_model import InvoicesCreateLineModel as InvoicesCreateLineModel
    from dolibarr_api.models.invoices_settodraft_model import InvoicesSettodraftModel as InvoicesSettodraftModel
    from dolibarr_api.models.invoices_settopaid_model import InvoicesSettopaidModel as InvoicesSettopaidModel
    from dolibarr_api.models.invoices_update_line_model import InvoicesUpdateLineModel as InvoicesUpdateLineModel
    from dolibarr_api.models.invoices_update_payment_model import InvoicesUpdatePaymentModel as InvoicesUpdatePaymentModel
    from dolibarr_api.models.invoices_validate_model import InvoicesValidateModel as InvoicesValidateModel
    from dolibarr_api.models.knowledgemanagement_cancel_model import KnowledgemanagementCancelModel as KnowledgemanagementCancelModel
    from dolibarr_api.models.knowledgemanagement_validate_model import KnowledgemanagementValidateModel as KnowledgemanagementValidateModel
    from dolibarr_api.models.list_login_model import ListLoginModel as ListLoginModel
    from dolibarr_api.models.members_create_subscription_model import MembersCreateSubscriptionModel as MembersCreateSubscriptionModel
    from dolibarr_api.models.members_create_type_model import MembersCreateTypeModel as MembersCreateTypeModel
    from dolibarr_api.models.members_update_type_model import MembersUpdateTypeModel as MembersUpdateTypeModel
    from dolibarr_api.models.multicurrencies_update_rate_model import MulticurrenciesUpdateRateModel as MulticurrenciesUpdateRateModel
    from dolibarr_api.models.obj import Obj as Obj
    from dolibarr_api.models.objectlinks_create_model import ObjectlinksCreateModel as ObjectlinksCreateModel
    from dolibarr_api.models.orders_close_model import OrdersCloseModel as OrdersCloseModel
    from dolibarr_api.models.orders_create_line_model import OrdersCreateLineModel as OrdersCreateLineModel
    from dolibarr_api.models.orders_settodraft_model import OrdersSettodraftModel as OrdersSettodraftModel
    from dolibarr_api.models.orders_update_line_model import OrdersUpdateLineModel as OrdersUpdateLineModel
    from dolibarr_api.models.orders_validate_model import OrdersValidateModel as OrdersValidateModel
    from dolibarr_api.models.products_add_attribute_value_model import ProductsAddAttributeValueModel as ProductsAddAttributeValueModel
    from dolibarr_api.models.products_add_attributes_model import ProductsAddAttributesModel as ProductsAddAttributesModel
    from dolibarr_api.models.products_add_purchase_price_model import ProductsAddPurchasePriceModel as ProductsAddPurchasePriceModel
    from dolibarr_api.models.products_add_subproducts_model import ProductsAddSubproductsModel as ProductsAddSubproductsModel
    from dolibarr_api.models.products_add_variant_by_product_ref_model import ProductsAddVariantByProductRefModel as ProductsAddVariantByProductRefModel
    from dolibarr_api.models.products_add_variant_model import ProductsAddVariantModel as ProductsAddVariantModel
    from dolibarr_api.models.products_update_attribute_value_model import ProductsUpdateAttributeValueModel as ProductsUpdateAttributeValueModel
    from dolibarr_api.models.products_update_attributes_model import ProductsUpdateAttributesModel as ProductsUpdateAttributesModel
    from dolibarr_api.models.products_update_variant_model import ProductsUpdateVariantModel as ProductsUpdateVariantModel
    from dolibarr_api.models.projects_validate_model import ProjectsValidateModel as ProjectsValidateModel
    from dolibarr_api.models.proposals_close_model import ProposalsCloseModel as ProposalsCloseModel
    from dolibarr_api.models.proposals_create_line_model import ProposalsCreateLineModel as ProposalsCreateLineModel
    from dolibarr_api.models.proposals_create_lines_model import ProposalsCreateLinesModel as ProposalsCreateLinesModel
    from dolibarr_api.models.proposals_update_line_model import ProposalsUpdateLineModel as ProposalsUpdateLineModel
    from dolibarr_api.models.proposals_validate_model import ProposalsValidateModel as ProposalsValidateModel
    from dolibarr_api.models.recruitments_create_candidature_model import RecruitmentsCreateCandidatureModel as RecruitmentsCreateCandidatureModel
    from dolibarr_api.models.recruitments_create_job_position_model import RecruitmentsCreateJobPositionModel as RecruitmentsCreateJobPositionModel
    from dolibarr_api.models.recruitments_update_candidature_model import RecruitmentsUpdateCandidatureModel as RecruitmentsUpdateCandidatureModel
    from dolibarr_api.models.recruitments_update_job_position_model import RecruitmentsUpdateJobPositionModel as RecruitmentsUpdateJobPositionModel
    from dolibarr_api.models.salaries_add_payment_model import SalariesAddPaymentModel as SalariesAddPaymentModel
    from dolibarr_api.models.salaries_update_payment_model import SalariesUpdatePaymentModel as SalariesUpdatePaymentModel
    from dolibarr_api.models.setup_create_extrafields_model import SetupCreateExtrafieldsModel as SetupCreateExtrafieldsModel
    from dolibarr_api.models.setup_update_extrafields_model import SetupUpdateExtrafieldsModel as SetupUpdateExtrafieldsModel
    from dolibarr_api.models.shipments_close_model import ShipmentsCloseModel as ShipmentsCloseModel
    from dolibarr_api.models.shipments_validate_model import ShipmentsValidateModel as ShipmentsValidateModel
    from dolibarr_api.models.supplierinvoices_add_payment_model import SupplierinvoicesAddPaymentModel as SupplierinvoicesAddPaymentModel
    from dolibarr_api.models.supplierinvoices_create_line_model import SupplierinvoicesCreateLineModel as SupplierinvoicesCreateLineModel
    from dolibarr_api.models.supplierinvoices_settodraft_model import SupplierinvoicesSettodraftModel as SupplierinvoicesSettodraftModel
    from dolibarr_api.models.supplierinvoices_update_line_model import SupplierinvoicesUpdateLineModel as SupplierinvoicesUpdateLineModel
    from dolibarr_api.models.supplierinvoices_validate_model import SupplierinvoicesValidateModel as SupplierinvoicesValidateModel
    from dolibarr_api.models.supplierorders_approve_model import SupplierordersApproveModel as SupplierordersApproveModel
    from dolibarr_api.models.supplierorders_make_order_model import SupplierordersMakeOrderModel as SupplierordersMakeOrderModel
    from dolibarr_api.models.supplierorders_receive_order_model import SupplierordersReceiveOrderModel as SupplierordersReceiveOrderModel
    from dolibarr_api.models.supplierorders_validate_model import SupplierordersValidateModel as SupplierordersValidateModel
    from dolibarr_api.models.tasks_add_time_spent_model import TasksAddTimeSpentModel as TasksAddTimeSpentModel
    from dolibarr_api.models.tasks_update_time_spent_model import TasksUpdateTimeSpentModel as TasksUpdateTimeSpentModel
    from dolibarr_api.models.thirdparties_create_company_bank_account_model import ThirdpartiesCreateCompanyBankAccountModel as ThirdpartiesCreateCompanyBankAccountModel
    from dolibarr_api.models.thirdparties_create_company_notification_by_code_model import ThirdpartiesCreateCompanyNotificationByCodeModel as ThirdpartiesCreateCompanyNotificationByCodeModel
    from dolibarr_api.models.thirdparties_create_company_notification_model import ThirdpartiesCreateCompanyNotificationModel as ThirdpartiesCreateCompanyNotificationModel
    from dolibarr_api.models.thirdparties_create_societe_account_model import ThirdpartiesCreateSocieteAccountModel as ThirdpartiesCreateSocieteAccountModel
    from dolibarr_api.models.thirdparties_update_company_bank_account_model import ThirdpartiesUpdateCompanyBankAccountModel as ThirdpartiesUpdateCompanyBankAccountModel
    from dolibarr_api.models.thirdparties_update_company_notification_model import ThirdpartiesUpdateCompanyNotificationModel as ThirdpartiesUpdateCompanyNotificationModel
    from dolibarr_api.models.thirdparties_update_societe_account_model import ThirdpartiesUpdateSocieteAccountModel as ThirdpartiesUpdateSocieteAccountModel
    from dolibarr_api.models.tickets_create_new_message_model import TicketsCreateNewMessageModel as TicketsCreateNewMessageModel
    from dolibarr_api.models.update_agendaevents_model import UpdateAgendaeventsModel as UpdateAgendaeventsModel
    from dolibarr_api.models.update_bankaccounts_model import UpdateBankaccountsModel as UpdateBankaccountsModel
    from dolibarr_api.models.update_categories_model import UpdateCategoriesModel as UpdateCategoriesModel
    from dolibarr_api.models.update_contacts_model import UpdateContactsModel as UpdateContactsModel
    from dolibarr_api.models.update_contracts_model import UpdateContractsModel as UpdateContractsModel
    from dolibarr_api.models.update_donations_model import UpdateDonationsModel as UpdateDonationsModel
    from dolibarr_api.models.update_expensereports_model import UpdateExpensereportsModel as UpdateExpensereportsModel
    from dolibarr_api.models.update_interventions_model import UpdateInterventionsModel as UpdateInterventionsModel
    from dolibarr_api.models.update_invoices_model import UpdateInvoicesModel as UpdateInvoicesModel
    from dolibarr_api.models.update_knowledgemanagement_model import UpdateKnowledgemanagementModel as UpdateKnowledgemanagementModel
    from dolibarr_api.models.update_members_model import UpdateMembersModel as UpdateMembersModel
    from dolibarr_api.models.update_memberstypes_model import UpdateMemberstypesModel as UpdateMemberstypesModel
    from dolibarr_api.models.update_multicurrencies_model import UpdateMulticurrenciesModel as UpdateMulticurrenciesModel
    from dolibarr_api.models.update_orders_model import UpdateOrdersModel as UpdateOrdersModel
    from dolibarr_api.models.update_partnerships_model import UpdatePartnershipsModel as UpdatePartnershipsModel
    from dolibarr_api.models.update_products_model import UpdateProductsModel as UpdateProductsModel
    from dolibarr_api.models.update_projects_model import UpdateProjectsModel as UpdateProjectsModel
    from dolibarr_api.models.update_proposals_model import UpdateProposalsModel as UpdateProposalsModel
    from dolibarr_api.models.update_salaries_model import UpdateSalariesModel as UpdateSalariesModel
    from dolibarr_api.models.update_shipments_model import UpdateShipmentsModel as UpdateShipmentsModel
    from dolibarr_api.models.update_subscriptions_model import UpdateSubscriptionsModel as UpdateSubscriptionsModel
    from dolibarr_api.models.update_supplierinvoices_model import UpdateSupplierinvoicesModel as UpdateSupplierinvoicesModel
    from dolibarr_api.models.update_supplierorders_model import UpdateSupplierordersModel as UpdateSupplierordersModel
    from dolibarr_api.models.update_supplierproposals_model import UpdateSupplierproposalsModel as UpdateSupplierproposalsModel
    from dolibarr_api.models.update_tasks_model import UpdateTasksModel as UpdateTasksModel
    from dolibarr_api.models.update_thirdparties_model import UpdateThirdpartiesModel as UpdateThirdpartiesModel
    from dolibarr_api.models.update_tickets_model import UpdateTicketsModel as UpdateTicketsModel
    from dolibarr_api.models.update_users_model import UpdateUsersModel as UpdateUsersModel
    from dolibarr_api.models.update_warehouses_model import UpdateWarehousesModel as UpdateWarehousesModel
    from dolibarr_api.models.users_create_user_notification_by_code_model import UsersCreateUserNotificationByCodeModel as UsersCreateUserNotificationByCodeModel
    from dolibarr_api.models.users_create_user_notification_model import UsersCreateUserNotificationModel as UsersCreateUserNotificationModel
    from dolibarr_api.models.users_update_user_notification_model import UsersUpdateUserNotificationModel as UsersUpdateUserNotificationModel
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from dolibarr_api.api.accountancy_api import AccountancyApi as AccountancyApi
from dolibarr_api.api.agendaevents_api import AgendaeventsApi as AgendaeventsApi
from dolibarr_api.api.bankaccounts_api import BankaccountsApi as BankaccountsApi
from dolibarr_api.api.categories_api import CategoriesApi as CategoriesApi
from dolibarr_api.api.contacts_api import ContactsApi as ContactsApi
from dolibarr_api.api.contracts_api import ContractsApi as ContractsApi
from dolibarr_api.api.documents_api import DocumentsApi as DocumentsApi
from dolibarr_api.api.donations_api import DonationsApi as DonationsApi
from dolibarr_api.api.eventattendees_api import EventattendeesApi as EventattendeesApi
from dolibarr_api.api.expensereports_api import ExpensereportsApi as ExpensereportsApi
from dolibarr_api.api.interventions_api import InterventionsApi as InterventionsApi
from dolibarr_api.api.invoices_api import InvoicesApi as InvoicesApi
from dolibarr_api.api.knowledgemanagement_api import KnowledgemanagementApi as KnowledgemanagementApi
from dolibarr_api.api.login_api import LoginApi as LoginApi
from dolibarr_api.api.members_api import MembersApi as MembersApi
from dolibarr_api.api.memberstypes_api import MemberstypesApi as MemberstypesApi
from dolibarr_api.api.multicurrencies_api import MulticurrenciesApi as MulticurrenciesApi
from dolibarr_api.api.objectlinks_api import ObjectlinksApi as ObjectlinksApi
from dolibarr_api.api.orders_api import OrdersApi as OrdersApi
from dolibarr_api.api.partnerships_api import PartnershipsApi as PartnershipsApi
from dolibarr_api.api.products_api import ProductsApi as ProductsApi
from dolibarr_api.api.projects_api import ProjectsApi as ProjectsApi
from dolibarr_api.api.proposals_api import ProposalsApi as ProposalsApi
from dolibarr_api.api.recruitments_api import RecruitmentsApi as RecruitmentsApi
from dolibarr_api.api.salaries_api import SalariesApi as SalariesApi
from dolibarr_api.api.setup_api import SetupApi as SetupApi
from dolibarr_api.api.shipments_api import ShipmentsApi as ShipmentsApi
from dolibarr_api.api.status_api import StatusApi as StatusApi
from dolibarr_api.api.stockmovements_api import StockmovementsApi as StockmovementsApi
from dolibarr_api.api.subscriptions_api import SubscriptionsApi as SubscriptionsApi
from dolibarr_api.api.supplierinvoices_api import SupplierinvoicesApi as SupplierinvoicesApi
from dolibarr_api.api.supplierorders_api import SupplierordersApi as SupplierordersApi
from dolibarr_api.api.supplierproposals_api import SupplierproposalsApi as SupplierproposalsApi
from dolibarr_api.api.tasks_api import TasksApi as TasksApi
from dolibarr_api.api.thirdparties_api import ThirdpartiesApi as ThirdpartiesApi
from dolibarr_api.api.tickets_api import TicketsApi as TicketsApi
from dolibarr_api.api.users_api import UsersApi as UsersApi
from dolibarr_api.api.warehouses_api import WarehousesApi as WarehousesApi

# import ApiClient
from dolibarr_api.api_response import ApiResponse as ApiResponse
from dolibarr_api.api_client import ApiClient as ApiClient
from dolibarr_api.configuration import Configuration as Configuration
from dolibarr_api.exceptions import OpenApiException as OpenApiException
from dolibarr_api.exceptions import ApiTypeError as ApiTypeError
from dolibarr_api.exceptions import ApiValueError as ApiValueError
from dolibarr_api.exceptions import ApiKeyError as ApiKeyError
from dolibarr_api.exceptions import ApiAttributeError as ApiAttributeError
from dolibarr_api.exceptions import ApiException as ApiException

# import models into sdk package
from dolibarr_api.models.bankaccounts_add_line_model import BankaccountsAddLineModel as BankaccountsAddLineModel
from dolibarr_api.models.bankaccounts_add_link_model import BankaccountsAddLinkModel as BankaccountsAddLinkModel
from dolibarr_api.models.bankaccounts_transfer_model import BankaccountsTransferModel as BankaccountsTransferModel
from dolibarr_api.models.bankaccounts_update_line_model import BankaccountsUpdateLineModel as BankaccountsUpdateLineModel
from dolibarr_api.models.contacts_create_user_model import ContactsCreateUserModel as ContactsCreateUserModel
from dolibarr_api.models.contracts_activate_line_model import ContractsActivateLineModel as ContractsActivateLineModel
from dolibarr_api.models.contracts_close_model import ContractsCloseModel as ContractsCloseModel
from dolibarr_api.models.contracts_create_line_model import ContractsCreateLineModel as ContractsCreateLineModel
from dolibarr_api.models.contracts_unactivate_line_model import ContractsUnactivateLineModel as ContractsUnactivateLineModel
from dolibarr_api.models.contracts_update_line_model import ContractsUpdateLineModel as ContractsUpdateLineModel
from dolibarr_api.models.contracts_validate_model import ContractsValidateModel as ContractsValidateModel
from dolibarr_api.models.create_agendaevents_model import CreateAgendaeventsModel as CreateAgendaeventsModel
from dolibarr_api.models.create_bankaccounts_model import CreateBankaccountsModel as CreateBankaccountsModel
from dolibarr_api.models.create_categories_model import CreateCategoriesModel as CreateCategoriesModel
from dolibarr_api.models.create_contacts_model import CreateContactsModel as CreateContactsModel
from dolibarr_api.models.create_contracts_model import CreateContractsModel as CreateContractsModel
from dolibarr_api.models.create_documents_model import CreateDocumentsModel as CreateDocumentsModel
from dolibarr_api.models.create_donations_model import CreateDonationsModel as CreateDonationsModel
from dolibarr_api.models.create_eventattendees_model import CreateEventattendeesModel as CreateEventattendeesModel
from dolibarr_api.models.create_expensereports_model import CreateExpensereportsModel as CreateExpensereportsModel
from dolibarr_api.models.create_interventions_model import CreateInterventionsModel as CreateInterventionsModel
from dolibarr_api.models.create_invoices_model import CreateInvoicesModel as CreateInvoicesModel
from dolibarr_api.models.create_knowledgemanagement_model import CreateKnowledgemanagementModel as CreateKnowledgemanagementModel
from dolibarr_api.models.create_members_model import CreateMembersModel as CreateMembersModel
from dolibarr_api.models.create_memberstypes_model import CreateMemberstypesModel as CreateMemberstypesModel
from dolibarr_api.models.create_multicurrencies_model import CreateMulticurrenciesModel as CreateMulticurrenciesModel
from dolibarr_api.models.create_orders_model import CreateOrdersModel as CreateOrdersModel
from dolibarr_api.models.create_partnerships_model import CreatePartnershipsModel as CreatePartnershipsModel
from dolibarr_api.models.create_products_model import CreateProductsModel as CreateProductsModel
from dolibarr_api.models.create_projects_model import CreateProjectsModel as CreateProjectsModel
from dolibarr_api.models.create_proposals_model import CreateProposalsModel as CreateProposalsModel
from dolibarr_api.models.create_salaries_model import CreateSalariesModel as CreateSalariesModel
from dolibarr_api.models.create_shipments_model import CreateShipmentsModel as CreateShipmentsModel
from dolibarr_api.models.create_stockmovements_model import CreateStockmovementsModel as CreateStockmovementsModel
from dolibarr_api.models.create_subscriptions_model import CreateSubscriptionsModel as CreateSubscriptionsModel
from dolibarr_api.models.create_supplierinvoices_model import CreateSupplierinvoicesModel as CreateSupplierinvoicesModel
from dolibarr_api.models.create_supplierorders_model import CreateSupplierordersModel as CreateSupplierordersModel
from dolibarr_api.models.create_supplierproposals_model import CreateSupplierproposalsModel as CreateSupplierproposalsModel
from dolibarr_api.models.create_tasks_model import CreateTasksModel as CreateTasksModel
from dolibarr_api.models.create_thirdparties_model import CreateThirdpartiesModel as CreateThirdpartiesModel
from dolibarr_api.models.create_tickets_model import CreateTicketsModel as CreateTicketsModel
from dolibarr_api.models.create_users_model import CreateUsersModel as CreateUsersModel
from dolibarr_api.models.create_warehouses_model import CreateWarehousesModel as CreateWarehousesModel
from dolibarr_api.models.documents_builddoc_model import DocumentsBuilddocModel as DocumentsBuilddocModel
from dolibarr_api.models.donations_validate_model import DonationsValidateModel as DonationsValidateModel
from dolibarr_api.models.eventattendees_update_by_id_model import EventattendeesUpdateByIdModel as EventattendeesUpdateByIdModel
from dolibarr_api.models.eventattendees_update_by_ref_model import EventattendeesUpdateByRefModel as EventattendeesUpdateByRefModel
from dolibarr_api.models.expensereports_add_payment_model import ExpensereportsAddPaymentModel as ExpensereportsAddPaymentModel
from dolibarr_api.models.expensereports_approve_model import ExpensereportsApproveModel as ExpensereportsApproveModel
from dolibarr_api.models.expensereports_deny_model import ExpensereportsDenyModel as ExpensereportsDenyModel
from dolibarr_api.models.expensereports_update_payment_model import ExpensereportsUpdatePaymentModel as ExpensereportsUpdatePaymentModel
from dolibarr_api.models.expensereports_validate_model import ExpensereportsValidateModel as ExpensereportsValidateModel
from dolibarr_api.models.interventions_create_line_model import InterventionsCreateLineModel as InterventionsCreateLineModel
from dolibarr_api.models.interventions_validate_model import InterventionsValidateModel as InterventionsValidateModel
from dolibarr_api.models.invoices_add_contact_model import InvoicesAddContactModel as InvoicesAddContactModel
from dolibarr_api.models.invoices_add_payment_distributed_model import InvoicesAddPaymentDistributedModel as InvoicesAddPaymentDistributedModel
from dolibarr_api.models.invoices_add_payment_model import InvoicesAddPaymentModel as InvoicesAddPaymentModel
from dolibarr_api.models.invoices_create_line_model import InvoicesCreateLineModel as InvoicesCreateLineModel
from dolibarr_api.models.invoices_settodraft_model import InvoicesSettodraftModel as InvoicesSettodraftModel
from dolibarr_api.models.invoices_settopaid_model import InvoicesSettopaidModel as InvoicesSettopaidModel
from dolibarr_api.models.invoices_update_line_model import InvoicesUpdateLineModel as InvoicesUpdateLineModel
from dolibarr_api.models.invoices_update_payment_model import InvoicesUpdatePaymentModel as InvoicesUpdatePaymentModel
from dolibarr_api.models.invoices_validate_model import InvoicesValidateModel as InvoicesValidateModel
from dolibarr_api.models.knowledgemanagement_cancel_model import KnowledgemanagementCancelModel as KnowledgemanagementCancelModel
from dolibarr_api.models.knowledgemanagement_validate_model import KnowledgemanagementValidateModel as KnowledgemanagementValidateModel
from dolibarr_api.models.list_login_model import ListLoginModel as ListLoginModel
from dolibarr_api.models.members_create_subscription_model import MembersCreateSubscriptionModel as MembersCreateSubscriptionModel
from dolibarr_api.models.members_create_type_model import MembersCreateTypeModel as MembersCreateTypeModel
from dolibarr_api.models.members_update_type_model import MembersUpdateTypeModel as MembersUpdateTypeModel
from dolibarr_api.models.multicurrencies_update_rate_model import MulticurrenciesUpdateRateModel as MulticurrenciesUpdateRateModel
from dolibarr_api.models.obj import Obj as Obj
from dolibarr_api.models.objectlinks_create_model import ObjectlinksCreateModel as ObjectlinksCreateModel
from dolibarr_api.models.orders_close_model import OrdersCloseModel as OrdersCloseModel
from dolibarr_api.models.orders_create_line_model import OrdersCreateLineModel as OrdersCreateLineModel
from dolibarr_api.models.orders_settodraft_model import OrdersSettodraftModel as OrdersSettodraftModel
from dolibarr_api.models.orders_update_line_model import OrdersUpdateLineModel as OrdersUpdateLineModel
from dolibarr_api.models.orders_validate_model import OrdersValidateModel as OrdersValidateModel
from dolibarr_api.models.products_add_attribute_value_model import ProductsAddAttributeValueModel as ProductsAddAttributeValueModel
from dolibarr_api.models.products_add_attributes_model import ProductsAddAttributesModel as ProductsAddAttributesModel
from dolibarr_api.models.products_add_purchase_price_model import ProductsAddPurchasePriceModel as ProductsAddPurchasePriceModel
from dolibarr_api.models.products_add_subproducts_model import ProductsAddSubproductsModel as ProductsAddSubproductsModel
from dolibarr_api.models.products_add_variant_by_product_ref_model import ProductsAddVariantByProductRefModel as ProductsAddVariantByProductRefModel
from dolibarr_api.models.products_add_variant_model import ProductsAddVariantModel as ProductsAddVariantModel
from dolibarr_api.models.products_update_attribute_value_model import ProductsUpdateAttributeValueModel as ProductsUpdateAttributeValueModel
from dolibarr_api.models.products_update_attributes_model import ProductsUpdateAttributesModel as ProductsUpdateAttributesModel
from dolibarr_api.models.products_update_variant_model import ProductsUpdateVariantModel as ProductsUpdateVariantModel
from dolibarr_api.models.projects_validate_model import ProjectsValidateModel as ProjectsValidateModel
from dolibarr_api.models.proposals_close_model import ProposalsCloseModel as ProposalsCloseModel
from dolibarr_api.models.proposals_create_line_model import ProposalsCreateLineModel as ProposalsCreateLineModel
from dolibarr_api.models.proposals_create_lines_model import ProposalsCreateLinesModel as ProposalsCreateLinesModel
from dolibarr_api.models.proposals_update_line_model import ProposalsUpdateLineModel as ProposalsUpdateLineModel
from dolibarr_api.models.proposals_validate_model import ProposalsValidateModel as ProposalsValidateModel
from dolibarr_api.models.recruitments_create_candidature_model import RecruitmentsCreateCandidatureModel as RecruitmentsCreateCandidatureModel
from dolibarr_api.models.recruitments_create_job_position_model import RecruitmentsCreateJobPositionModel as RecruitmentsCreateJobPositionModel
from dolibarr_api.models.recruitments_update_candidature_model import RecruitmentsUpdateCandidatureModel as RecruitmentsUpdateCandidatureModel
from dolibarr_api.models.recruitments_update_job_position_model import RecruitmentsUpdateJobPositionModel as RecruitmentsUpdateJobPositionModel
from dolibarr_api.models.salaries_add_payment_model import SalariesAddPaymentModel as SalariesAddPaymentModel
from dolibarr_api.models.salaries_update_payment_model import SalariesUpdatePaymentModel as SalariesUpdatePaymentModel
from dolibarr_api.models.setup_create_extrafields_model import SetupCreateExtrafieldsModel as SetupCreateExtrafieldsModel
from dolibarr_api.models.setup_update_extrafields_model import SetupUpdateExtrafieldsModel as SetupUpdateExtrafieldsModel
from dolibarr_api.models.shipments_close_model import ShipmentsCloseModel as ShipmentsCloseModel
from dolibarr_api.models.shipments_validate_model import ShipmentsValidateModel as ShipmentsValidateModel
from dolibarr_api.models.supplierinvoices_add_payment_model import SupplierinvoicesAddPaymentModel as SupplierinvoicesAddPaymentModel
from dolibarr_api.models.supplierinvoices_create_line_model import SupplierinvoicesCreateLineModel as SupplierinvoicesCreateLineModel
from dolibarr_api.models.supplierinvoices_settodraft_model import SupplierinvoicesSettodraftModel as SupplierinvoicesSettodraftModel
from dolibarr_api.models.supplierinvoices_update_line_model import SupplierinvoicesUpdateLineModel as SupplierinvoicesUpdateLineModel
from dolibarr_api.models.supplierinvoices_validate_model import SupplierinvoicesValidateModel as SupplierinvoicesValidateModel
from dolibarr_api.models.supplierorders_approve_model import SupplierordersApproveModel as SupplierordersApproveModel
from dolibarr_api.models.supplierorders_make_order_model import SupplierordersMakeOrderModel as SupplierordersMakeOrderModel
from dolibarr_api.models.supplierorders_receive_order_model import SupplierordersReceiveOrderModel as SupplierordersReceiveOrderModel
from dolibarr_api.models.supplierorders_validate_model import SupplierordersValidateModel as SupplierordersValidateModel
from dolibarr_api.models.tasks_add_time_spent_model import TasksAddTimeSpentModel as TasksAddTimeSpentModel
from dolibarr_api.models.tasks_update_time_spent_model import TasksUpdateTimeSpentModel as TasksUpdateTimeSpentModel
from dolibarr_api.models.thirdparties_create_company_bank_account_model import ThirdpartiesCreateCompanyBankAccountModel as ThirdpartiesCreateCompanyBankAccountModel
from dolibarr_api.models.thirdparties_create_company_notification_by_code_model import ThirdpartiesCreateCompanyNotificationByCodeModel as ThirdpartiesCreateCompanyNotificationByCodeModel
from dolibarr_api.models.thirdparties_create_company_notification_model import ThirdpartiesCreateCompanyNotificationModel as ThirdpartiesCreateCompanyNotificationModel
from dolibarr_api.models.thirdparties_create_societe_account_model import ThirdpartiesCreateSocieteAccountModel as ThirdpartiesCreateSocieteAccountModel
from dolibarr_api.models.thirdparties_update_company_bank_account_model import ThirdpartiesUpdateCompanyBankAccountModel as ThirdpartiesUpdateCompanyBankAccountModel
from dolibarr_api.models.thirdparties_update_company_notification_model import ThirdpartiesUpdateCompanyNotificationModel as ThirdpartiesUpdateCompanyNotificationModel
from dolibarr_api.models.thirdparties_update_societe_account_model import ThirdpartiesUpdateSocieteAccountModel as ThirdpartiesUpdateSocieteAccountModel
from dolibarr_api.models.tickets_create_new_message_model import TicketsCreateNewMessageModel as TicketsCreateNewMessageModel
from dolibarr_api.models.update_agendaevents_model import UpdateAgendaeventsModel as UpdateAgendaeventsModel
from dolibarr_api.models.update_bankaccounts_model import UpdateBankaccountsModel as UpdateBankaccountsModel
from dolibarr_api.models.update_categories_model import UpdateCategoriesModel as UpdateCategoriesModel
from dolibarr_api.models.update_contacts_model import UpdateContactsModel as UpdateContactsModel
from dolibarr_api.models.update_contracts_model import UpdateContractsModel as UpdateContractsModel
from dolibarr_api.models.update_donations_model import UpdateDonationsModel as UpdateDonationsModel
from dolibarr_api.models.update_expensereports_model import UpdateExpensereportsModel as UpdateExpensereportsModel
from dolibarr_api.models.update_interventions_model import UpdateInterventionsModel as UpdateInterventionsModel
from dolibarr_api.models.update_invoices_model import UpdateInvoicesModel as UpdateInvoicesModel
from dolibarr_api.models.update_knowledgemanagement_model import UpdateKnowledgemanagementModel as UpdateKnowledgemanagementModel
from dolibarr_api.models.update_members_model import UpdateMembersModel as UpdateMembersModel
from dolibarr_api.models.update_memberstypes_model import UpdateMemberstypesModel as UpdateMemberstypesModel
from dolibarr_api.models.update_multicurrencies_model import UpdateMulticurrenciesModel as UpdateMulticurrenciesModel
from dolibarr_api.models.update_orders_model import UpdateOrdersModel as UpdateOrdersModel
from dolibarr_api.models.update_partnerships_model import UpdatePartnershipsModel as UpdatePartnershipsModel
from dolibarr_api.models.update_products_model import UpdateProductsModel as UpdateProductsModel
from dolibarr_api.models.update_projects_model import UpdateProjectsModel as UpdateProjectsModel
from dolibarr_api.models.update_proposals_model import UpdateProposalsModel as UpdateProposalsModel
from dolibarr_api.models.update_salaries_model import UpdateSalariesModel as UpdateSalariesModel
from dolibarr_api.models.update_shipments_model import UpdateShipmentsModel as UpdateShipmentsModel
from dolibarr_api.models.update_subscriptions_model import UpdateSubscriptionsModel as UpdateSubscriptionsModel
from dolibarr_api.models.update_supplierinvoices_model import UpdateSupplierinvoicesModel as UpdateSupplierinvoicesModel
from dolibarr_api.models.update_supplierorders_model import UpdateSupplierordersModel as UpdateSupplierordersModel
from dolibarr_api.models.update_supplierproposals_model import UpdateSupplierproposalsModel as UpdateSupplierproposalsModel
from dolibarr_api.models.update_tasks_model import UpdateTasksModel as UpdateTasksModel
from dolibarr_api.models.update_thirdparties_model import UpdateThirdpartiesModel as UpdateThirdpartiesModel
from dolibarr_api.models.update_tickets_model import UpdateTicketsModel as UpdateTicketsModel
from dolibarr_api.models.update_users_model import UpdateUsersModel as UpdateUsersModel
from dolibarr_api.models.update_warehouses_model import UpdateWarehousesModel as UpdateWarehousesModel
from dolibarr_api.models.users_create_user_notification_by_code_model import UsersCreateUserNotificationByCodeModel as UsersCreateUserNotificationByCodeModel
from dolibarr_api.models.users_create_user_notification_model import UsersCreateUserNotificationModel as UsersCreateUserNotificationModel
from dolibarr_api.models.users_update_user_notification_model import UsersUpdateUserNotificationModel as UsersUpdateUserNotificationModel

""",
            name=__name__,
            doc=__doc__,
        )
    )
