# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated

from dolibarr_api.api_client import ApiClient, RequestSerialized
from dolibarr_api.api_response import ApiResponse
from dolibarr_api.rest import RESTResponseType


class AccountancyApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def accountancy_export_data(
        self,
        period: Annotated[StrictStr, Field(description="Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above)")],
        date_min: Annotated[Optional[StrictStr], Field(description="[=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        date_max: Annotated[Optional[StrictStr], Field(description="[=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        format: Annotated[Optional[StrictStr], Field(description="[=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)")] = None,
        lettering: Annotated[Optional[StrictInt], Field(description="[=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)")] = None,
        alreadyexport: Annotated[Optional[StrictInt], Field(description="[=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)")] = None,
        notnotifiedasexport: Annotated[Optional[StrictInt], Field(description="[=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Accountancy export data 🔐


        :param period: Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above) (required)
        :type period: str
        :param date_min: [=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_min: str
        :param date_max: [=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_max: str
        :param format: [=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)
        :type format: str
        :param lettering: [=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)
        :type lettering: int
        :param alreadyexport: [=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)
        :type alreadyexport: int
        :param notnotifiedasexport: [=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')
        :type notnotifiedasexport: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accountancy_export_data_serialize(
            period=period,
            date_min=date_min,
            date_max=date_max,
            format=format,
            lettering=lettering,
            alreadyexport=alreadyexport,
            notnotifiedasexport=notnotifiedasexport,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '401': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def accountancy_export_data_with_http_info(
        self,
        period: Annotated[StrictStr, Field(description="Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above)")],
        date_min: Annotated[Optional[StrictStr], Field(description="[=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        date_max: Annotated[Optional[StrictStr], Field(description="[=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        format: Annotated[Optional[StrictStr], Field(description="[=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)")] = None,
        lettering: Annotated[Optional[StrictInt], Field(description="[=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)")] = None,
        alreadyexport: Annotated[Optional[StrictInt], Field(description="[=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)")] = None,
        notnotifiedasexport: Annotated[Optional[StrictInt], Field(description="[=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Accountancy export data 🔐


        :param period: Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above) (required)
        :type period: str
        :param date_min: [=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_min: str
        :param date_max: [=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_max: str
        :param format: [=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)
        :type format: str
        :param lettering: [=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)
        :type lettering: int
        :param alreadyexport: [=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)
        :type alreadyexport: int
        :param notnotifiedasexport: [=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')
        :type notnotifiedasexport: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accountancy_export_data_serialize(
            period=period,
            date_min=date_min,
            date_max=date_max,
            format=format,
            lettering=lettering,
            alreadyexport=alreadyexport,
            notnotifiedasexport=notnotifiedasexport,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '401': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def accountancy_export_data_without_preload_content(
        self,
        period: Annotated[StrictStr, Field(description="Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above)")],
        date_min: Annotated[Optional[StrictStr], Field(description="[=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        date_max: Annotated[Optional[StrictStr], Field(description="[=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'")] = None,
        format: Annotated[Optional[StrictStr], Field(description="[=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)")] = None,
        lettering: Annotated[Optional[StrictInt], Field(description="[=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)")] = None,
        alreadyexport: Annotated[Optional[StrictInt], Field(description="[=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)")] = None,
        notnotifiedasexport: Annotated[Optional[StrictInt], Field(description="[=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Accountancy export data 🔐


        :param period: Period : 'lastmonth', 'currentmonth', 'last3months', 'last6months', 'currentyear', 'lastyear', 'fiscalyear', 'lastfiscalyear', 'actualandlastfiscalyear' or 'custom' (see above) (required)
        :type period: str
        :param date_min: [=''] Start date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_min: str
        :param date_max: [=''] End date of period if 'custom' is set in period parameter Date format is 'YYYY-MM-DD'
        :type date_max: str
        :param format: [=''] by default uses '1' for 'Configurable (CSV)' for format number or '1000' for FEC or '1010' for FEC2 (see AccountancyExport class)
        :type format: str
        :param lettering: [=0] by default don't export or 1 to export lettering data (columns 'letterring_code' and 'date_lettering' returns empty or not)
        :type lettering: int
        :param alreadyexport: [=0] by default export data only if it's not yet exported or 1 already exported (always export data even if 'date_export\" is set)
        :type alreadyexport: int
        :param notnotifiedasexport: [=0] by default notified as exported or 1 not notified as exported (when the export is done, notified or not the column 'date_export')
        :type notnotifiedasexport: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._accountancy_export_data_serialize(
            period=period,
            date_min=date_min,
            date_max=date_max,
            format=format,
            lettering=lettering,
            alreadyexport=alreadyexport,
            notnotifiedasexport=notnotifiedasexport,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '401': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _accountancy_export_data_serialize(
        self,
        period,
        date_min,
        date_max,
        format,
        lettering,
        alreadyexport,
        notnotifiedasexport,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if period is not None:
            
            _query_params.append(('period', period))
            
        if date_min is not None:
            
            _query_params.append(('date_min', date_min))
            
        if date_max is not None:
            
            _query_params.append(('date_max', date_max))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        if lettering is not None:
            
            _query_params.append(('lettering', lettering))
            
        if alreadyexport is not None:
            
            _query_params.append(('alreadyexport', alreadyexport))
            
        if notnotifiedasexport is not None:
            
            _query_params.append(('notnotifiedasexport', notnotifiedasexport))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/xml'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/accountancy/exportdata',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


