# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from dolibarr_api.models.create_stockmovements_model import CreateStockmovementsModel

from dolibarr_api.api_client import ApiClient, RequestSerialized
from dolibarr_api.api_response import ApiResponse
from dolibarr_api.rest import RESTResponseType


class StockmovementsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_stockmovements(
        self,
        create_stockmovements_model: Annotated[CreateStockmovementsModel, Field(description="**product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id   ")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> int:
        """Create stock movement object. 🔐

        You can use the following message to test this RES API: { \"product_id\": 1, \"warehouse_id\": 1, \"qty\": 1, \"lot\": \"\", \"movementcode\": \"INV123\", \"movementlabel\": \"Inventory 123\", \"price\": 0 } $price Can be set to update AWP (Average Weighted Price) when you make a stock increase $dlc Eat-by date. Will be used if lot does not exists yet and will be created. $dluo Sell-by date. Will be used if lot does not exists yet and will be created.

        :param create_stockmovements_model: **product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id    (required)
        :type create_stockmovements_model: CreateStockmovementsModel
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_stockmovements_serialize(
            create_stockmovements_model=create_stockmovements_model,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "int",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_stockmovements_with_http_info(
        self,
        create_stockmovements_model: Annotated[CreateStockmovementsModel, Field(description="**product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id   ")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[int]:
        """Create stock movement object. 🔐

        You can use the following message to test this RES API: { \"product_id\": 1, \"warehouse_id\": 1, \"qty\": 1, \"lot\": \"\", \"movementcode\": \"INV123\", \"movementlabel\": \"Inventory 123\", \"price\": 0 } $price Can be set to update AWP (Average Weighted Price) when you make a stock increase $dlc Eat-by date. Will be used if lot does not exists yet and will be created. $dluo Sell-by date. Will be used if lot does not exists yet and will be created.

        :param create_stockmovements_model: **product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id    (required)
        :type create_stockmovements_model: CreateStockmovementsModel
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_stockmovements_serialize(
            create_stockmovements_model=create_stockmovements_model,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "int",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_stockmovements_without_preload_content(
        self,
        create_stockmovements_model: Annotated[CreateStockmovementsModel, Field(description="**product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id   ")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create stock movement object. 🔐

        You can use the following message to test this RES API: { \"product_id\": 1, \"warehouse_id\": 1, \"qty\": 1, \"lot\": \"\", \"movementcode\": \"INV123\", \"movementlabel\": \"Inventory 123\", \"price\": 0 } $price Can be set to update AWP (Average Weighted Price) when you make a stock increase $dlc Eat-by date. Will be used if lot does not exists yet and will be created. $dluo Sell-by date. Will be used if lot does not exists yet and will be created.

        :param create_stockmovements_model: **product_id** (required)   **warehouse_id** (required)   **qty** (required)   type   lot   movementcode   movementlabel   price   datem   dlc   dluo   origin_type   origin_id    (required)
        :type create_stockmovements_model: CreateStockmovementsModel
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_stockmovements_serialize(
            create_stockmovements_model=create_stockmovements_model,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "int",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_stockmovements_serialize(
        self,
        create_stockmovements_model,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if create_stockmovements_model is not None:
            _body_params = create_stockmovements_model


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/xml'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json', 
                        'application/xml', 
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/stockmovements',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_stockmovements(
        self,
        sortfield: Annotated[Optional[StrictStr], Field(description="Sort field")] = None,
        sortorder: Annotated[Optional[StrictStr], Field(description="Sort order")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Limit for list")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number")] = None,
        sqlfilters: Annotated[Optional[StrictStr], Field(description="Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"")] = None,
        properties: Annotated[Optional[StrictStr], Field(description="Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[str]:
        """Get a list of stock movement 🔐


        :param sortfield: Sort field
        :type sortfield: str
        :param sortorder: Sort order
        :type sortorder: str
        :param limit: Limit for list
        :type limit: int
        :param page: Page number
        :type page: int
        :param sqlfilters: Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"
        :type sqlfilters: str
        :param properties: Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names
        :type properties: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_stockmovements_serialize(
            sortfield=sortfield,
            sortorder=sortorder,
            limit=limit,
            page=page,
            sqlfilters=sqlfilters,
            properties=properties,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_stockmovements_with_http_info(
        self,
        sortfield: Annotated[Optional[StrictStr], Field(description="Sort field")] = None,
        sortorder: Annotated[Optional[StrictStr], Field(description="Sort order")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Limit for list")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number")] = None,
        sqlfilters: Annotated[Optional[StrictStr], Field(description="Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"")] = None,
        properties: Annotated[Optional[StrictStr], Field(description="Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[str]]:
        """Get a list of stock movement 🔐


        :param sortfield: Sort field
        :type sortfield: str
        :param sortorder: Sort order
        :type sortorder: str
        :param limit: Limit for list
        :type limit: int
        :param page: Page number
        :type page: int
        :param sqlfilters: Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"
        :type sqlfilters: str
        :param properties: Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names
        :type properties: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_stockmovements_serialize(
            sortfield=sortfield,
            sortorder=sortorder,
            limit=limit,
            page=page,
            sqlfilters=sqlfilters,
            properties=properties,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_stockmovements_without_preload_content(
        self,
        sortfield: Annotated[Optional[StrictStr], Field(description="Sort field")] = None,
        sortorder: Annotated[Optional[StrictStr], Field(description="Sort order")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Limit for list")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number")] = None,
        sqlfilters: Annotated[Optional[StrictStr], Field(description="Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"")] = None,
        properties: Annotated[Optional[StrictStr], Field(description="Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get a list of stock movement 🔐


        :param sortfield: Sort field
        :type sortfield: str
        :param sortorder: Sort order
        :type sortorder: str
        :param limit: Limit for list
        :type limit: int
        :param page: Page number
        :type page: int
        :param sqlfilters: Other criteria to filter answers separated by a comma. Syntax example \"(t.fk_product:=:1) and (t.date_creation:<:'20160101')\"
        :type sqlfilters: str
        :param properties: Restrict the data returned to these properties. Ignored if empty. Comma separated list of properties names
        :type properties: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_stockmovements_serialize(
            sortfield=sortfield,
            sortorder=sortorder,
            limit=limit,
            page=page,
            sqlfilters=sqlfilters,
            properties=properties,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[str]",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_stockmovements_serialize(
        self,
        sortfield,
        sortorder,
        limit,
        page,
        sqlfilters,
        properties,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if sortfield is not None:
            
            _query_params.append(('sortfield', sortfield))
            
        if sortorder is not None:
            
            _query_params.append(('sortorder', sortorder))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if sqlfilters is not None:
            
            _query_params.append(('sqlfilters', sqlfilters))
            
        if properties is not None:
            
            _query_params.append(('properties', properties))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/xml'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/stockmovements',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


