# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class BankaccountsAddLineModel(BaseModel):
    """
    BankaccountsAddLineModel
    """ # noqa: E501
    var_date: StrictStr = Field(description="Payment date (timestamp)", alias="date")
    type: StrictStr = Field(description="Payment mode (TYP,VIR,PRE,LIQ,VAD,CB,CHQ...)")
    label: StrictStr = Field(description="Label")
    amount: Union[StrictFloat, StrictInt] = Field(description="Amount (may be 0)")
    category: Optional[StrictInt] = Field(default=None, description="Category")
    cheque_number: Optional[StrictStr] = Field(default=None, description="Cheque numero")
    cheque_writer: Optional[StrictStr] = Field(default=None, description="Name of cheque writer")
    cheque_bank: Optional[StrictStr] = Field(default=None, description="Bank of cheque writer")
    accountancycode: Optional[StrictStr] = Field(default=None, description="Accountancy code")
    datev: Optional[StrictStr] = Field(default=None, description="Payment date value (timestamp)")
    num_releve: Optional[StrictStr] = Field(default=None, description="Bank statement numero")
    __properties: ClassVar[List[str]] = ["date", "type", "label", "amount", "category", "cheque_number", "cheque_writer", "cheque_bank", "accountancycode", "datev", "num_releve"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankaccountsAddLineModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankaccountsAddLineModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "type": obj.get("type"),
            "label": obj.get("label"),
            "amount": obj.get("amount"),
            "category": obj.get("category"),
            "cheque_number": obj.get("cheque_number"),
            "cheque_writer": obj.get("cheque_writer"),
            "cheque_bank": obj.get("cheque_bank"),
            "accountancycode": obj.get("accountancycode"),
            "datev": obj.get("datev"),
            "num_releve": obj.get("num_releve")
        })
        return _obj


