# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InvoicesAddContactModel(BaseModel):
    """
    InvoicesAddContactModel
    """ # noqa: E501
    fk_socpeople: StrictInt = Field(description="Id of thirdparty contact (if source = 'external') or id of user (if source = 'internal') to link")
    type_contact: StrictStr = Field(description="Type of contact (code). Must a code found into table llx_c_type_contact. For example: BILLING")
    source: StrictStr = Field(description="external=Contact extern (llx_socpeople), internal=Contact intern (llx_user)")
    notrigger: Optional[StrictInt] = Field(default=None, description="Disable all triggers")
    __properties: ClassVar[List[str]] = ["fk_socpeople", "type_contact", "source", "notrigger"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoicesAddContactModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoicesAddContactModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fk_socpeople": obj.get("fk_socpeople"),
            "type_contact": obj.get("type_contact"),
            "source": obj.get("source"),
            "notrigger": obj.get("notrigger")
        })
        return _obj


