# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.bankaccounts_api import BankaccountsApi


class TestBankaccountsApi(unittest.TestCase):
    """BankaccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankaccountsApi()

    def tearDown(self) -> None:
        pass

    def test_bankaccounts_add_line(self) -> None:
        """Test case for bankaccounts_add_line

        Add a line to an account 🔐
        """
        pass

    def test_bankaccounts_add_link(self) -> None:
        """Test case for bankaccounts_add_link

        Add a link to an account line 🔐
        """
        pass

    def test_bankaccounts_remove_line(self) -> None:
        """Test case for bankaccounts_remove_line

        Delete an account line 🔐
        """
        pass

    def test_bankaccounts_retrieve_balance(self) -> None:
        """Test case for bankaccounts_retrieve_balance

        Get current account balance by ID 🔐
        """
        pass

    def test_bankaccounts_retrieve_lines(self) -> None:
        """Test case for bankaccounts_retrieve_lines

        Get the list of lines of the account. 🔐
        """
        pass

    def test_bankaccounts_retrieve_links(self) -> None:
        """Test case for bankaccounts_retrieve_links

        Get the list of links for a line of the account. 🔐
        """
        pass

    def test_bankaccounts_transfer(self) -> None:
        """Test case for bankaccounts_transfer

        Create an internal wire transfer between two bank accounts 🔐
        """
        pass

    def test_bankaccounts_update_line(self) -> None:
        """Test case for bankaccounts_update_line

        Update an account line 🔐
        """
        pass

    def test_create_bankaccounts(self) -> None:
        """Test case for create_bankaccounts

        Create account object 🔐
        """
        pass

    def test_list_bankaccounts(self) -> None:
        """Test case for list_bankaccounts

        Get the list of accounts. 🔐
        """
        pass

    def test_remove_bankaccounts(self) -> None:
        """Test case for remove_bankaccounts

        Delete account 🔐
        """
        pass

    def test_retrieve_bankaccounts(self) -> None:
        """Test case for retrieve_bankaccounts

        Get account by ID. 🔐
        """
        pass

    def test_update_bankaccounts(self) -> None:
        """Test case for update_bankaccounts

        Update account 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
