# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.setup_api import SetupApi


class TestSetupApi(unittest.TestCase):
    """SetupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SetupApi()

    def tearDown(self) -> None:
        pass

    def test_setup_create_extrafields(self) -> None:
        """Test case for setup_create_extrafields

        Create Extrafield object 🔐
        """
        pass

    def test_setup_remove_extrafields_from_names(self) -> None:
        """Test case for setup_remove_extrafields_from_names

        Delete extrafield 🔐
        """
        pass

    def test_setup_retrieve_availability(self) -> None:
        """Test case for setup_retrieve_availability

        Get the list of delivery times. 🔐
        """
        pass

    def test_setup_retrieve_check_integrity(self) -> None:
        """Test case for setup_retrieve_check_integrity

        Do a test of integrity for files and setup. 🔐
        """
        pass

    def test_setup_retrieve_company(self) -> None:
        """Test case for setup_retrieve_company

        Get properties of company 🔐
        """
        pass

    def test_setup_retrieve_conf(self) -> None:
        """Test case for setup_retrieve_conf

        Get value of a setup variables 🔐
        """
        pass

    def test_setup_retrieve_confs(self) -> None:
        """Test case for setup_retrieve_confs

        Get all setup variables 🔐
        """
        pass

    def test_setup_retrieve_country_by_code(self) -> None:
        """Test case for setup_retrieve_country_by_code

        Get country by Code. 🔐
        """
        pass

    def test_setup_retrieve_country_by_id(self) -> None:
        """Test case for setup_retrieve_country_by_id

        Get country by ID. 🔐
        """
        pass

    def test_setup_retrieve_country_by_iso(self) -> None:
        """Test case for setup_retrieve_country_by_iso

        Get country by Iso. 🔐
        """
        pass

    def test_setup_retrieve_establishments(self) -> None:
        """Test case for setup_retrieve_establishments

        Get the list of establishments. 🔐
        """
        pass

    def test_setup_retrieve_etablishment_by_id(self) -> None:
        """Test case for setup_retrieve_etablishment_by_id

        Get establishment by ID. 🔐
        """
        pass

    def test_setup_retrieve_extrafields(self) -> None:
        """Test case for setup_retrieve_extrafields

         🔐
        """
        pass

    def test_setup_retrieve_list_of_action_triggers(self) -> None:
        """Test case for setup_retrieve_list_of_action_triggers

        Get the list of Action Triggers. 🔐
        """
        pass

    def test_setup_retrieve_list_of_civilities(self) -> None:
        """Test case for setup_retrieve_list_of_civilities

        Get the list of civilities. 🔐
        """
        pass

    def test_setup_retrieve_list_of_contact_types(self) -> None:
        """Test case for setup_retrieve_list_of_contact_types

        Get the list of contacts types. 🔐
        """
        pass

    def test_setup_retrieve_list_of_countries(self) -> None:
        """Test case for setup_retrieve_list_of_countries

        Get the list of countries. 🔐
        """
        pass

    def test_setup_retrieve_list_of_currencies(self) -> None:
        """Test case for setup_retrieve_list_of_currencies

        Get the list of currencies. 🔐
        """
        pass

    def test_setup_retrieve_list_of_event_types(self) -> None:
        """Test case for setup_retrieve_list_of_event_types

        Get the list of events types. 🔐
        """
        pass

    def test_setup_retrieve_list_of_expense_reports_types(self) -> None:
        """Test case for setup_retrieve_list_of_expense_reports_types

        Get the list of Expense Report types. 🔐
        """
        pass

    def test_setup_retrieve_list_of_extrafields(self) -> None:
        """Test case for setup_retrieve_list_of_extrafields

        Get the list of extra fields. 🔐
        """
        pass

    def test_setup_retrieve_list_of_incoterms(self) -> None:
        """Test case for setup_retrieve_list_of_incoterms

        Get the list of incoterms. 🔐
        """
        pass

    def test_setup_retrieve_list_of_legal_form(self) -> None:
        """Test case for setup_retrieve_list_of_legal_form

        Get the list of legal form of business. 🔐
        """
        pass

    def test_setup_retrieve_list_of_measuring_units(self) -> None:
        """Test case for setup_retrieve_list_of_measuring_units

        Get the list of measuring units. 🔐
        """
        pass

    def test_setup_retrieve_list_of_regions(self) -> None:
        """Test case for setup_retrieve_list_of_regions

        Get the list of regions. 🔐
        """
        pass

    def test_setup_retrieve_list_of_staff(self) -> None:
        """Test case for setup_retrieve_list_of_staff

        Get the list of staff. 🔐
        """
        pass

    def test_setup_retrieve_list_of_states(self) -> None:
        """Test case for setup_retrieve_list_of_states

        Get the list of states/provinces. 🔐
        """
        pass

    def test_setup_retrieve_list_of_towns(self) -> None:
        """Test case for setup_retrieve_list_of_towns

        Get the list of towns. 🔐
        """
        pass

    def test_setup_retrieve_list_ofsocial_networks(self) -> None:
        """Test case for setup_retrieve_list_ofsocial_networks

        Get the list of social networks. 🔐
        """
        pass

    def test_setup_retrieve_modules(self) -> None:
        """Test case for setup_retrieve_modules

        Get list of enabled modules 🔐
        """
        pass

    def test_setup_retrieve_ordering_methods(self) -> None:
        """Test case for setup_retrieve_ordering_methods

        Get the list of ordering methods. 🔐
        """
        pass

    def test_setup_retrieve_ordering_origins(self) -> None:
        """Test case for setup_retrieve_ordering_origins

        Get the list of ordering origins. 🔐
        """
        pass

    def test_setup_retrieve_payment_terms(self) -> None:
        """Test case for setup_retrieve_payment_terms

        Get the list of payments terms. 🔐
        """
        pass

    def test_setup_retrieve_payment_types(self) -> None:
        """Test case for setup_retrieve_payment_types

        Get the list of payments types. 🔐
        """
        pass

    def test_setup_retrieve_region_by_code(self) -> None:
        """Test case for setup_retrieve_region_by_code

        Get region by Code. 🔐
        """
        pass

    def test_setup_retrieve_region_by_id(self) -> None:
        """Test case for setup_retrieve_region_by_id

        Get region by ID. 🔐
        """
        pass

    def test_setup_retrieve_shipping_modes(self) -> None:
        """Test case for setup_retrieve_shipping_modes

        Get the list of shipping methods. 🔐
        """
        pass

    def test_setup_retrieve_state_by_code(self) -> None:
        """Test case for setup_retrieve_state_by_code

        Get state by Code. 🔐
        """
        pass

    def test_setup_retrieve_state_by_id(self) -> None:
        """Test case for setup_retrieve_state_by_id

        Get state by ID. 🔐
        """
        pass

    def test_setup_retrieve_tickets_categories(self) -> None:
        """Test case for setup_retrieve_tickets_categories

        Get the list of tickets categories. 🔐
        """
        pass

    def test_setup_retrieve_tickets_severities(self) -> None:
        """Test case for setup_retrieve_tickets_severities

        Get the list of tickets severity. 🔐
        """
        pass

    def test_setup_retrieve_tickets_types(self) -> None:
        """Test case for setup_retrieve_tickets_types

        Get the list of tickets types. 🔐
        """
        pass

    def test_setup_update_extrafields(self) -> None:
        """Test case for setup_update_extrafields

        Update Extrafield object 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
