# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.warehouses_api import WarehousesApi


class TestWarehousesApi(unittest.TestCase):
    """WarehousesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WarehousesApi()

    def tearDown(self) -> None:
        pass

    def test_create_warehouses(self) -> None:
        """Test case for create_warehouses

        Create warehouse object 🔐
        """
        pass

    def test_list_warehouses(self) -> None:
        """Test case for list_warehouses

        List warehouses 🔐
        """
        pass

    def test_remove_warehouses(self) -> None:
        """Test case for remove_warehouses

        Delete warehouse 🔐
        """
        pass

    def test_retrieve_warehouses(self) -> None:
        """Test case for retrieve_warehouses

        Get properties of a warehouse object 🔐
        """
        pass

    def test_update_warehouses(self) -> None:
        """Test case for update_warehouses

        Update warehouse 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
