# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.proposals_api import ProposalsApi


class TestProposalsApi(unittest.TestCase):
    """ProposalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProposalsApi()

    def tearDown(self) -> None:
        pass

    def test_create_proposals(self) -> None:
        """Test case for create_proposals

        Create a commercial proposal 🔐
        """
        pass

    def test_list_proposals(self) -> None:
        """Test case for list_proposals

        List commercial proposals 🔐
        """
        pass

    def test_proposals_close(self) -> None:
        """Test case for proposals_close

        Close (accept or refuse) a commercial proposal 🔐
        """
        pass

    def test_proposals_create_contact(self) -> None:
        """Test case for proposals_create_contact

        Add (link) a contact to a commercial proposal 🔐
        """
        pass

    def test_proposals_create_line(self) -> None:
        """Test case for proposals_create_line

        Add a line to a commercial proposal 🔐
        """
        pass

    def test_proposals_create_lines(self) -> None:
        """Test case for proposals_create_lines

        Add lines to a commercial proposal 🔐
        """
        pass

    def test_proposals_remove_contact(self) -> None:
        """Test case for proposals_remove_contact

        Remove (unlink) a contact from commercial proposal 🔐
        """
        pass

    def test_proposals_remove_line(self) -> None:
        """Test case for proposals_remove_line

        Delete a line of a commercial proposal 🔐
        """
        pass

    def test_proposals_retrieve_by_ref(self) -> None:
        """Test case for proposals_retrieve_by_ref

        Get a commercial proposal by ref 🔐
        """
        pass

    def test_proposals_retrieve_by_ref_ext(self) -> None:
        """Test case for proposals_retrieve_by_ref_ext

        Get a commercial proposal by ref_ext 🔐
        """
        pass

    def test_proposals_retrieve_lines(self) -> None:
        """Test case for proposals_retrieve_lines

        Get lines of a commercial proposal 🔐
        """
        pass

    def test_proposals_setinvoiced(self) -> None:
        """Test case for proposals_setinvoiced

        Set a commercial proposal to billed 🔐
        """
        pass

    def test_proposals_settodraft(self) -> None:
        """Test case for proposals_settodraft

        Set a commercial proposal to draft 🔐
        """
        pass

    def test_proposals_update_line(self) -> None:
        """Test case for proposals_update_line

        Update a line of a commercial proposal 🔐
        """
        pass

    def test_proposals_validate(self) -> None:
        """Test case for proposals_validate

        Validate a commercial proposal 🔐
        """
        pass

    def test_remove_proposals(self) -> None:
        """Test case for remove_proposals

        Delete a commercial proposal 🔐
        """
        pass

    def test_retrieve_proposals(self) -> None:
        """Test case for retrieve_proposals

        Get a commercial proposal 🔐
        """
        pass

    def test_update_proposals(self) -> None:
        """Test case for update_proposals

        Update a commercial proposal general fields (won't change lines of commercial proposal) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
