# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_create_projects(self) -> None:
        """Test case for create_projects

        Create project object 🔐
        """
        pass

    def test_list_projects(self) -> None:
        """Test case for list_projects

        List projects 🔐
        """
        pass

    def test_projects_retrieve_by_msg_id(self) -> None:
        """Test case for projects_retrieve_by_msg_id

        Get properties of a project object 🔐
        """
        pass

    def test_projects_retrieve_by_ref(self) -> None:
        """Test case for projects_retrieve_by_ref

        Get properties of a project object 🔐
        """
        pass

    def test_projects_retrieve_by_ref_ext(self) -> None:
        """Test case for projects_retrieve_by_ref_ext

        Get properties of a project object 🔐
        """
        pass

    def test_projects_retrieve_lines(self) -> None:
        """Test case for projects_retrieve_lines

        Get tasks of a project. 🔐
        """
        pass

    def test_projects_retrieve_roles(self) -> None:
        """Test case for projects_retrieve_roles

        Get roles a user is assigned to a project with 🔐
        """
        pass

    def test_projects_validate(self) -> None:
        """Test case for projects_validate

        Validate a project. 🔐
        """
        pass

    def test_remove_projects(self) -> None:
        """Test case for remove_projects

        Delete project 🔐
        """
        pass

    def test_retrieve_projects(self) -> None:
        """Test case for retrieve_projects

        Get properties of a project object 🔐
        """
        pass

    def test_update_projects(self) -> None:
        """Test case for update_projects

        Update project general fields (won't touch lines of project) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
