# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.eventattendees_api import EventattendeesApi


class TestEventattendeesApi(unittest.TestCase):
    """EventattendeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventattendeesApi()

    def tearDown(self) -> None:
        pass

    def test_create_eventattendees(self) -> None:
        """Test case for create_eventattendees

        Create an event attendee 🔐
        """
        pass

    def test_eventattendees_remove_by_id(self) -> None:
        """Test case for eventattendees_remove_by_id

        Delete an event attendee 🔐
        """
        pass

    def test_eventattendees_remove_by_ref(self) -> None:
        """Test case for eventattendees_remove_by_ref

        Delete an event attendee 🔐
        """
        pass

    def test_eventattendees_retrieve_by_id(self) -> None:
        """Test case for eventattendees_retrieve_by_id

        Get properties of a event attendee by id 🔐
        """
        pass

    def test_eventattendees_retrieve_by_ref(self) -> None:
        """Test case for eventattendees_retrieve_by_ref

        Get properties of an event attendee by ref 🔐
        """
        pass

    def test_eventattendees_update_by_id(self) -> None:
        """Test case for eventattendees_update_by_id

        Update an event attendee 🔐
        """
        pass

    def test_eventattendees_update_by_ref(self) -> None:
        """Test case for eventattendees_update_by_ref

        Update an event attendee 🔐
        """
        pass

    def test_list_eventattendees(self) -> None:
        """Test case for list_eventattendees

        List Event attendees 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
