# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.supplierorders_api import SupplierordersApi


class TestSupplierordersApi(unittest.TestCase):
    """SupplierordersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SupplierordersApi()

    def tearDown(self) -> None:
        pass

    def test_create_supplierorders(self) -> None:
        """Test case for create_supplierorders

        Create supplier order object 🔐
        """
        pass

    def test_list_supplierorders(self) -> None:
        """Test case for list_supplierorders

        List orders 🔐
        """
        pass

    def test_remove_supplierorders(self) -> None:
        """Test case for remove_supplierorders

        Delete supplier order 🔐
        """
        pass

    def test_retrieve_supplierorders(self) -> None:
        """Test case for retrieve_supplierorders

        Get properties of a supplier order object 🔐
        """
        pass

    def test_supplierorders_approve(self) -> None:
        """Test case for supplierorders_approve

        Approve an order 🔐
        """
        pass

    def test_supplierorders_create_contact(self) -> None:
        """Test case for supplierorders_create_contact

        Add a contact type of given supplier order 🔐
        """
        pass

    def test_supplierorders_make_order(self) -> None:
        """Test case for supplierorders_make_order

        Sends an order to the vendor 🔐
        """
        pass

    def test_supplierorders_receive_order(self) -> None:
        """Test case for supplierorders_receive_order

        Receives the order, dispatches products. 🔐
        """
        pass

    def test_supplierorders_remove_contact(self) -> None:
        """Test case for supplierorders_remove_contact

        Unlink a contact type of given supplier order 🔐
        """
        pass

    def test_supplierorders_retrieve_contacts(self) -> None:
        """Test case for supplierorders_retrieve_contacts

        Get contacts of given supplier order 🔐
        """
        pass

    def test_supplierorders_validate(self) -> None:
        """Test case for supplierorders_validate

        Validate an order 🔐
        """
        pass

    def test_update_supplierorders(self) -> None:
        """Test case for update_supplierorders

        Update supplier order 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
