# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.knowledgemanagement_api import KnowledgemanagementApi


class TestKnowledgemanagementApi(unittest.TestCase):
    """KnowledgemanagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KnowledgemanagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_knowledgemanagement(self) -> None:
        """Test case for create_knowledgemanagement

        Create knowledgerecord object 🔐
        """
        pass

    def test_knowledgemanagement_cancel(self) -> None:
        """Test case for knowledgemanagement_cancel

        Cancel a knowledge 🔐
        """
        pass

    def test_knowledgemanagement_retrieve_categories(self) -> None:
        """Test case for knowledgemanagement_retrieve_categories

        Get categories for a knowledgerecord object 🔐
        """
        pass

    def test_knowledgemanagement_validate(self) -> None:
        """Test case for knowledgemanagement_validate

        Validate a knowledge 🔐
        """
        pass

    def test_list_knowledgemanagement(self) -> None:
        """Test case for list_knowledgemanagement

        List knowledgerecords 🔐
        """
        pass

    def test_remove_knowledgemanagement(self) -> None:
        """Test case for remove_knowledgemanagement

        Delete knowledgerecord 🔐
        """
        pass

    def test_retrieve_knowledgemanagement(self) -> None:
        """Test case for retrieve_knowledgemanagement

        Get properties of a knowledgerecord object 🔐
        """
        pass

    def test_update_knowledgemanagement(self) -> None:
        """Test case for update_knowledgemanagement

        Update knowledgerecord 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
