# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dolibarr_api.api.interventions_api import InterventionsApi


class TestInterventionsApi(unittest.TestCase):
    """InterventionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InterventionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_interventions(self) -> None:
        """Test case for create_interventions

        Create an intervention 🔐
        """
        pass

    def test_interventions_close_fichinter(self) -> None:
        """Test case for interventions_close_fichinter

        Close an intervention 🔐
        """
        pass

    def test_interventions_create_line(self) -> None:
        """Test case for interventions_create_line

        Add a line to an intervention 🔐
        """
        pass

    def test_interventions_reopen(self) -> None:
        """Test case for interventions_reopen

        Reopen an intervention 🔐
        """
        pass

    def test_interventions_validate(self) -> None:
        """Test case for interventions_validate

        Validate an intervention 🔐
        """
        pass

    def test_list_interventions(self) -> None:
        """Test case for list_interventions

        List interventions 🔐
        """
        pass

    def test_remove_interventions(self) -> None:
        """Test case for remove_interventions

        Delete an intervention 🔐
        """
        pass

    def test_retrieve_interventions(self) -> None:
        """Test case for retrieve_interventions

        Get an intervention Return an array with intervention information 🔐
        """
        pass

    def test_update_interventions(self) -> None:
        """Test case for update_interventions

        Update intervention general fields (won't touch lines of fichinter) 🔐
        """
        pass


if __name__ == '__main__':
    unittest.main()
