# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "dolibarr-api"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Restler API Explorer",
    author="Restler Support",
    author_email="arul@luracast.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Restler API Explorer"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="LGPL-2.1",
    long_description_content_type='text/markdown',
    long_description="""\
    Live API Documentation
    """,  # noqa: E501
    package_data={"dolibarr_api": ["py.typed"]},
)