# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Obj(BaseModel):
    """
    Obj
    """ # noqa: E501
    string_encoder_function: StrictStr = Field(alias="stringEncoderFunction")
    number_encoder_function: StrictStr = Field(alias="numberEncoderFunction")
    fix: List[StrictStr] = Field(description="key value pairs for fixing value types using functions. For example 'id'=>'intval' will make sure all values of the id properties will be converted to integers intval function 'password'=> null will remove all the password entries")
    separator_char: StrictStr = Field(description="character that is used to identify sub objects For example when Object::$separatorChar = '.'; array('my.object'=>true) will result in array( 'my'=>array('object'=>true) );", alias="separatorChar")
    remove_empty: StrictBool = Field(description="set it to true when empty arrays, blank strings, null values to be automatically removed from response", alias="removeEmpty")
    remove_null: StrictBool = Field(description="set it to true to remove all null values from the result", alias="removeNull")
    __properties: ClassVar[List[str]] = ["stringEncoderFunction", "numberEncoderFunction", "fix", "separatorChar", "removeEmpty", "removeNull"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Obj from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Obj from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "stringEncoderFunction": obj.get("stringEncoderFunction"),
            "numberEncoderFunction": obj.get("numberEncoderFunction"),
            "fix": obj.get("fix"),
            "separatorChar": obj.get("separatorChar"),
            "removeEmpty": obj.get("removeEmpty"),
            "removeNull": obj.get("removeNull")
        })
        return _obj


