# coding: utf-8

"""
    Restler API Explorer

    Live API Documentation

    The version of the OpenAPI document: 1
    Contact: arul@luracast.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SupplierinvoicesAddPaymentModel(BaseModel):
    """
    SupplierinvoicesAddPaymentModel
    """ # noqa: E501
    datepaye: StrictStr = Field(description="Payment date")
    payment_mode_id: Annotated[int, Field(strict=True, ge=1)] = Field(description="Payment mode ID (look it up via REST GET to /setup/dictionary/payment_types)")
    closepaidinvoices: StrictStr = Field(description="Close paid invoices")
    accountid: Annotated[int, Field(strict=True, ge=1)] = Field(description="Bank account ID (look it up via REST GET to /bankaccounts)")
    num_payment: Optional[StrictStr] = Field(default=None, description="Payment number (optional)")
    comment: Optional[StrictStr] = Field(default=None, description="Note (optional)")
    chqemetteur: Optional[StrictStr] = Field(default=None, description="Payment issuer (mandatory if payment_mode_id corresponds to 'CHQ'-payment type)")
    chqbank: Optional[StrictStr] = Field(default=None, description="Issuer bank name (optional)")
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount of payment if we don't want to use the remain to pay")
    __properties: ClassVar[List[str]] = ["datepaye", "payment_mode_id", "closepaidinvoices", "accountid", "num_payment", "comment", "chqemetteur", "chqbank", "amount"]

    @field_validator('closepaidinvoices')
    def closepaidinvoices_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['yes', 'no']):
            raise ValueError("must be one of enum values ('yes', 'no')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SupplierinvoicesAddPaymentModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SupplierinvoicesAddPaymentModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datepaye": obj.get("datepaye"),
            "payment_mode_id": obj.get("payment_mode_id"),
            "closepaidinvoices": obj.get("closepaidinvoices"),
            "accountid": obj.get("accountid"),
            "num_payment": obj.get("num_payment"),
            "comment": obj.get("comment"),
            "chqemetteur": obj.get("chqemetteur"),
            "chqbank": obj.get("chqbank"),
            "amount": obj.get("amount")
        })
        return _obj


